### ISSUE TITLE
Gitcoin Bot still spams

### ISSUE THREAD

**Issue by lazaridiscom** [gitcoinco/web#4434] opened 2019-05-17 17:02 UTC
(this is possibly the 3rd time i report this, first time nearly a year ago)

Gitcoin bot keeps spamming issues, distracting again and again with irrelevant pings, see as an example this issue:

https://github.com/TrustWallet/wallet-core/issues/260#issuecomment-492129593

The bugs:

* Bot logic does not detect PRs / PR comments
* Bot logic does not detect issue comments

The Flaws:

* The default-reminder of 3 days is too early

**Comment by kuhnchris** [comment] 2019-05-17 20:55
Well, the description asks for commenting ON the issue, not on a PR, asking us to traverse PRs would probably kill our github api quota once and for all. 

That being said, for requests like yours, please ping @PixelantDesign @danlipert @vs77bb or any other of the gitcoin team members, they can set the reminders to about 100 days, which should help for your case.

**Comment by lazaridiscom** [comment] 2019-05-18 04:00
???

The bot spams, just fix it.

**Comment by kuhnchris** [comment] 2019-05-19 16:44
@PixelantDesign @vs77bb @danlipert the bot keeps spamming althou we suspended it for 100d.
Please check.

**Comment by kuhnchris** [comment] 2019-05-20 10:37
After short discussion with @PixelantDesign here are some ideas for @vs77bb / @owocki  / @danlipert / whoever is on the team right now to check:
- Check if this issue is maybe multiple times in the database
- Check if maybe my authorisations are not sufficient anymore for snoozing 100d
- Set the gitcoinbot check date for this issue to next year
- try to blacklist the issue for now if nothing else works.

This doesn't fix the core issue, but would at least serve as a reason why this is not working as intended right now.

**Comment by lazaridiscom** [comment] 2019-05-20 13:18
17 contributors...

https://github.com/gitcoinco/web/blob/5fe0b5a90d876e0ba9ff83769143927059e966ba/app/dashboard/notifications.py

The code needs to be refactored a little bit, mainly moving the state-machine related code to an own file, so maintenance becomes easier.

I noticed that the issue-count is >1K, still, the bot defect is of high-severity, simply because it makes gitcoin look unprofessional.

**Comment by owocki** [comment] 2019-05-20 14:23
hoping to have time to look into the root fix for this soon, in leiu of that - i just set the snooze_days to 10000000 instead of 100

**Comment by kuhnchris** [comment] 2019-05-20 16:40
negative @owocki
![grafik](https://user-images.githubusercontent.com/761911/58037851-b3658e00-7b2e-11e9-8a13-3ffcbd4b8794.png)

**Comment by owocki** [comment] 2019-05-20 18:50
5dea572fde5fe090f7a9b3537c9b248aabdc48a0 should help; still testing to make sure it fixes root cause

**Comment by kuhnchris** [comment] 2019-05-21 10:07
@owocki did you block the original poster?
![grafik](https://user-images.githubusercontent.com/761911/58087550-0e47c580-7bc1-11e9-8b86-c43019ad9161.png)

**Comment by owocki** [comment] 2019-05-21 16:56
@kuhnchris yes, Lazaridis has been warned repeatedly about our code of conduct after repeatedly violating it and has refused to change his behaviour.

I'm still committed to fixing the root issue.

**Comment by owocki** [comment] 2019-05-24 13:36
looks like my fix for the gitcoinbot issue worked!  closing this issue now

**Closed by owocki** 2019-05-24 13:36 UTC
Labels: bug
