### ISSUE TITLE
Idena verify callback wrong url

### ISSUE THREAD

**Issue by developerfred** [gitcoinco/web#8046] opened 2020-12-07 13:43 UTC
**Describe the bug**

When I verify my identity instead of idena returning to the trust bonus he redirects me to the page of a user called `@ trust`

**Comment by apbendi** [comment] 2020-12-07 16:23
Thanks for reporting @developerfred. Can I ask, were you connecting your Idena node, but are not yet validated when this happened? Or are you actually validated on Idena when this occurred? Appreciate it.

**Comment by apbendi** [comment] 2020-12-07 16:55
hey @developerfred, I'm unable to reproduce this issue. For me, the callback directs to https://gitcoin.co/profile/trust, which *should* bring you to the trust bonus page of the logged in user, which is what we want. Can you 1) confirm that clicking the link above does bring you to *your* trust bonus page and 2) Let me know if that's definitely not where you were redirected last time? I'm also still curious about the previously posted question, to see if that has any impact.

**Comment by developerfred** [comment] 2020-12-07 17:41
@apbendi My account is not verified, I believe it is because of that. Now when I log in pending verification appears.

**Comment by apbendi** [comment] 2020-12-07 19:00
hey @developerfred what happens if you click this link: https://gitcoin.co/profile/trust

**Comment by apbendi** [comment] 2020-12-08 15:46
Hi @developerfred, any update on this? As far as we can tell, the service is working correctly and redirecting to the URL above, which is configured to show the Trust Bonus of the logged in user. Unless you report otherwise, I'm going to close out this issue. Thanks again!

**Comment by apbendi** [comment] 2020-12-08 22:34
Closing for now, as I don't believe there's an issue. LMK if you feel otherwise.

**Closed by apbendi** 2020-12-08 22:34 UTC
Labels: round-8-support
