### ISSUE TITLE
bug - You must be authenticated via github to use this feature when using Faucet

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#2104] opened 2018-08-27 17:21 UTC
From user Sean F over email:

```
I want to fund an issue in one of my repos. I downloaded MetaMask, unlocked it, then the message on your site changed to View Faucet. I clicked the Profile link, authorized via github, my github username shows up, I add a comment, and when I click Proceed I get the following error:

There was an error:
Something went wrong submitting your request:
You must be authenticated via github to use this feature! 

How can I get past this error?

```

Looks like he is authenticated via github, but the system doesnt think he is?

**Comment by thelostone-mc** [comment] 2018-08-28 11:12
He would not have seen his profile in that case 🤔 
Cause that's how it's wired up!

Can he / @owocki  reproduce it ? I'm not able it

**Comment by thelostone-mc** [comment] 2018-09-13 09:15
Closing this out on account of unable to reproduce. will re-open if it happens again !

**Closed by thelostone-mc** 2018-09-13 09:15 UTC
Labels: bug, unable to reproduce
