### ISSUE TITLE
Gitcoin Grants Showing Donation of 0.0

### ISSUE THREAD

**Issue by fluxresearch** [gitcoinco/web#8540] opened 2021-03-11 11:17 UTC
I've noticed that some of the donations on my Gitcoin grant for CryptoArtNet say 0.00

What's going on with that? Why are they listed as donations at all?

Thanks!

https://gitcoin.co/grants/2122/cryptoartnet-artist-directory

**Comment by fluxresearch** [comment] 2021-03-12 02:12
I don't really need to understand the why but I do need to know if these Zero donations are spam and if I should report them.

I've got one individual with a series of 5 such empty donations?

If I'm missing something I need to know. If not, I need to address the issue with the tools at hand.

Could really use some help here. Thank you!

**Comment by fluxresearch** [comment] 2021-03-12 02:29
Also I don't see how to add the gr9-support label someone added to my previous question.

Would love to be able to maneuver better but I'm doing the best I can!

**Comment by nopslip** [comment] 2021-03-12 18:19
Thanks for reporting this. I've tracked down some 0.00 value donations and it looks to be that it might simply be that someone unintentionally checked out with a bunch of of 0.0 value donations.  I will confirm/deny that 0 value donations are indeed not restricted and let you know what I find out.

**Comment by lthrift** [comment] 2022-03-10 04:16
I'm going to close this since it is from GR9 and we have made several updates since this. If the issue is recurring during GR13, please report to support@gitcoin.co

**Closed by lthrift** 2022-03-10 04:16 UTC
