### ISSUE TITLE
Closed issues (on github) seems to be listed as open (on gitcoin)

### ISSUE THREAD

**Issue by dolebas** [gitcoinco/web#526] opened 2018-03-05 08:44 UTC
##### Description

Closed issues appears in the list when status "open" is selected, see screenshots.

![image](https://user-images.githubusercontent.com/27515901/36965256-702abb46-2059-11e8-8087-f6a51d30fd2b.png)

![image](https://user-images.githubusercontent.com/27515901/36965298-8a54d380-2059-11e8-9e38-9940e134707b.png)

**Comment by owocki** [comment] 2018-03-06 01:08
(I acknowledge this is confusing) The gitcoin.co explorer shows the **Gitcoin status** (top), which is open... but the Github status (bottom) is closed.

I just closed the Gitcoin issue in question ( https://gitcoin.co/funding/details?url=https://github.com/gitcoinco/web/issues/165 ) so that there's no further confusion

**Comment by dolebas** [comment] 2018-03-06 08:39
Have been browsing the issues on Gitcoin from time to time and it's great to see all the development.

Would be sweet if there was a filter for issues that no one has started working on, and a filter for all issues that are still open on Github. Manually finding these is a little time consuming at the moment.

**Comment by owocki** [comment] 2018-03-06 09:37
Thanks @dolebas -- great to have you ! 

[theres a filter on the left hand side](http://bits.owocki.com/360A2d1e0s43/Screen%20Shot%202018-03-06%20at%202.37.02%20AM.png) of https://gitcoin.co/explorer that you can use to see work that no one has started on... but to your point, we need to figure out a way to represent the openness of an issue on github on Gitcoin.co

**Comment by dolebas** [comment] 2018-03-06 09:56
Can't figure out which option is for filtering out issues that no one has started on.. Which is it?

It also looks like the "Started work" status on gitcoin.co is not consistent with the gitcoinbot on Github.

**Comment by owocki** [comment] 2018-03-06 10:04
> Can't figure out which option is for filtering out issues that no one has started on.. Which is it?

is the `1. open`. status, just before `2. work started`!

> It also looks like the "Started work" status on gitcoin.co is not consistent with the gitcoinbot on Github.
thanks for the bug report.. just put in a root cause fix here => 
 https://github.com/gitcoinco/web/commit/e05fb20c92fa2f02adff38044846f9ab969405fb -- i am going to go through the current issues and make sure they're all updated now.

**Comment by owocki** [comment] 2018-03-06 10:13
> i am going to go through the current issues and make sure they're all updated now.

updated!

**Comment by dolebas** [comment] 2018-03-06 10:30
Yes, that was what I assumed from the beginning, and the order is intuitive :P

But "1. open" doesn't seem to do what it is supposed to.

![image](https://user-images.githubusercontent.com/27515901/37027470-a4fb86d8-2131-11e8-9d85-a87ea885128e.png)

**Comment by owocki** [comment] 2018-03-06 10:37
hmmm.. strangely [i'm not able to reproduce the above](http://bits.owocki.com/0C0O1n0l1540/Screen%20Shot%202018-03-06%20at%203.36.42%20AM.png).. im guessing there is a caching issue afoot.. let me noodle on this

**Comment by dolebas** [comment] 2018-03-06 10:47
Super, feel free to reach out if there's anything I can assist with!

**Comment by kuhnchris** [comment] 2019-08-01 13:58
I guess this topic is not relevant anymore as we did many changes regarding the explorer - so I'm closing this. If the problem persists, please open a new issue.

**Closed by kuhnchris** 2019-08-01 13:58 UTC
