### ISSUE TITLE
I cannot cancel my Grant

### ISSUE THREAD

**Issue by dancespiele** [gitcoinco/web#7223] opened 2020-08-11 21:43 UTC
**Describe the bug**

I try to cancel the grant to create a new one because I cannot see the way to update the twitter link but when I click in the button cancel this grant I get a Modal which I click in the confirm button but nothing happens
**To Reproduce**

* Go to your Grant profile
* Click in the button `Cancel this Grant`
* In the modal click again `Cancel this Grant`
* You will see that nothing happens but in the console log you will get an error
**Expected behavior**

I should be able to cancel Grants
**Screenshots**

```
Uncaught TypeError: compiledSubscription is undefined
    <anonymous> detail.433240f9bdf6.js:205
    jQuery 2
    d raven.js:445
```
**Desktop (please complete the following information):**

- OS: Solus
- Browser: Firefox
- Browser Version:  79.0

**Smartphone (please complete the following information):**

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by owocki** [comment] 2020-08-11 22:16
@zoek1 i think we need to migrate the gratns (which previously relied upon a contract to cancel) to be able to be canceled directly in the DB

**Comment by thelostone-mc** [comment] 2020-08-24 09:43
@dancespiele 
@owocki is right on that ! If you can tell us which grant of yours you'd like to be closed, we can close it up on our end

**Comment by dancespiele** [comment] 2020-08-24 11:58
@thelostone-mc  thanks for your reply. Don't worry I preffer to update the twitter according with your answer for this issue https://github.com/gitcoinco/web/issues/7222 which you said that you can do. I will send to you the details there.

**Comment by zoek1** [comment] 2020-08-24 12:14
> @zoek1 i think we need to migrate the gratns (which previously relied upon a contract to cancel) to be able to be canceled directly in the DB

I didn't see this. Added to my todolist 👍

**Comment by alexander-morris** [comment] 2020-09-09 16:36
We are experiencing the same issue here. I created this, but can't seem to cancel it. https://gitcoin.co/grants/1116/weteachblockchain-free-decentralized-education

**Comment by owocki** [comment] 2020-09-09 21:56
@zoek1 think you can fit this one in before round 7 starts?

**Comment by owocki** [comment] 2020-09-10 02:41
e4b36f7b7bdc657bfc2f2b339371d67b0f245873 fixes the root cause

**Comment by GriffGreen** [comment] 2020-09-11 17:51
YAY!

**Comment by GriffGreen** [comment] 2020-09-12 01:04
> [e4b36f7](https://github.com/gitcoinco/web/commit/e4b36f7b7bdc657bfc2f2b339371d67b0f245873) fixes the root cause

<img width="483" alt="Screen Shot 2020-09-12 at 1 41 20 AM" src="https://user-images.githubusercontent.com/14945613/92983587-97fd5f80-f4a4-11ea-8f0f-51de21d61150.png">

**Comment by GriffGreen** [comment] 2020-09-13 18:13
Also... can we just make the cancel stuff happen on the front end so we don't have to pay gas to cancel the grant :-D

**Comment by alexander-morris** [comment] 2020-09-13 21:21
Sorry for all the trouble guys. If I just fund the wallet I created the grant with, can I pay the gas to cancel it myself?

**Comment by owocki** [comment] 2020-09-14 01:50
were deploying a change tomorrow that ll make it so u dont have to submit a txn to cancel the grant. pls hang tight

**Closed** 2020-09-14 19:23 UTC
Labels: grants_round_7

**Comment by GriffGreen** [comment] 2020-09-16 22:36
FUCKING HEROES! Thank you :-D

**Comment by alexander-morris** [comment] 2020-09-16 23:01
It works! Thanks guys :)
