### ISSUE TITLE
Cannot Contribute to Grant: Error

### ISSUE THREAD

**Issue by NodiumX** [gitcoinco/web#6932] opened 2020-06-20 09:03 UTC
While checking out of the cart with selected grants. It showing error Cannot read property 'enable' of undefined. Using formatic for checkout. 

**Describe the bug**
 The bug is not allowing to confirm the checkout and is showing error

**To Reproduce**
 First go and select a Grant, Add to Cart, Checkout, Click Fund items and the error will show. 
Using Wallet Formatic for checkout 

**Expected behavior**
 Display Error: Cannot read property 'enable' of undefined

**Screenshots**

![Error](https://user-images.githubusercontent.com/44767223/85197996-9b98a480-b302-11ea-96f8-2efc82dae71a.png)

**Comment by mds1** [comment] 2020-06-22 13:02
I think the issue is coming from this line in the checkout flow. https://github.com/gitcoinco/web/blob/31f9afa52076386e5a01ecb9edc3d2177ee3ba2e/app/assets/v2/js/cart.js#L501

@NodiumX Can you confirm that when connected with Fortmatic, if you click the dropdown arrow next to the Fortmatic logo in the toolbar it looks like the screenshot below? It should show your address and ETH balance as shown.
![image](https://user-images.githubusercontent.com/17163988/85286969-6e560e80-b448-11ea-8380-b4bdb30eedf4.png)

I've tried connecting with Fortmatic and initiating the checkout process and was not able to reproduce this, so my thinking is that your wallet may not connected properly. cc @octavioamu

**Comment by owocki** [comment] 2020-06-22 13:23
can you please fill out the required fields in the bug report template, including what browser you are on and what web3 wallet you are using?

**Comment by bmann** [comment] 2020-06-23 06:23
I'm getting the same thing, Chrome, MacOS Catalina, connected with WalletConnect.

Using Trust Wallet on iOS.

Here's my dropdown:

<img width="199" alt="Screen Shot 2020-06-22 at 11 21 25 PM" src="https://user-images.githubusercontent.com/280420/85367959-20d8b080-b4df-11ea-930b-03ca3c5094aa.png">

**Comment by bmann** [comment] 2020-06-23 06:29
Tried again on Safari on MacOS, got a different error message:

`undefined is not an object (evaluating 'window.ethereum.enable')`

**Comment by mds1** [comment] 2020-06-23 12:18
> I think the issue is coming from this line in the checkout flow.
> 
> https://github.com/gitcoinco/web/blob/31f9afa52076386e5a01ecb9edc3d2177ee3ba2e/app/assets/v2/js/cart.js#L501

@octavioamu Can we safely remove this line? This was added in before the web3Modal PR to ensure MetaMask was unlocked, so I think this is now unnecessary

**Comment by mds1** [comment] 2020-06-26 21:22
@octavioamu Got another report of this today, the error was `Cannot read property 'enable' of undefined`. Using Argent wallet via WalletConnect on Chrome.

Any idea how to resolve this?

**Comment by octavioamu** [comment] 2020-06-29 21:43
@mds1 I just deployed a fix for this https://github.com/gitcoinco/web/commit/d0ecb6e4db857c30d6ebf8649de66c664d4bf764#diff-ebd56e657002d50efb25041944ee2d6eL559

**Comment by octavioamu** [comment] 2020-06-29 21:45
also seems was a problem with the version of fortmatic sdk making the tx event to get into a loop sending emails for each event and failing. But now should be good

**Closed** 2020-06-29 21:46 UTC
