### ISSUE TITLE
Buggy Heartache

### ISSUE THREAD

**Issue by molecula451** [gitcoinco/web#6069] opened 2020-02-24 19:35 UTC
**Describe the bug**
Buggy heartache 

![heartache](https://user-images.githubusercontent.com/41552663/75184695-2bdf2800-571b-11ea-81e9-990e50e6a3d4.png)

**To Reproduce**

Click Like many time as soon as page is refreshed

**Expected behavior**
One like per user?

**Comment by molecula451** [comment] 2020-02-24 19:38
@owocki

**Comment by PixelantDesign** [comment] 2020-02-28 19:54
hmm maybe this is fixed. I can only like once.

**Comment by molecula451** [comment] 2020-02-28 19:56
@PixelantDesign try likes in "My Profile" Section

**Comment by PixelantDesign** [comment] 2020-03-02 15:03
Just tried it in the profile, didn't have any issues with more than one <3

**Comment by molecula451** [comment] 2020-03-02 22:12
@PixelantDesign Just saw another user posting about this same issue

**Comment by thelostone-mc** [comment] 2021-06-16 06:25
Closing this as I'm not able to reproduce this

**Closed by thelostone-mc** 2021-06-16 06:25 UTC
Labels: For Contributor, Hacktoberfest, enhancement, good first issue
