### ISSUE TITLE
Sending Kudos to yourself

### ISSUE THREAD

**Issue by kuhnchris** [gitcoinco/web#2578] opened 2018-10-30 21:49 UTC
**Describe the bug**
Right now you can send yourself Kudos

**To Reproduce**
Send yourself Kudos

**Expected behavior**
Not being able to send yourself Kudos

**Screenshots**
![image](https://user-images.githubusercontent.com/761911/47752848-e715bf00-dc95-11e8-9c0e-43870484021c.png)

**Desktop (please complete the following information):**

- OS: Mac OS X HIgh Sierra
- Browser Chrome
- Browser Version Latest Stable

**Comment by PixelantDesign** [comment] 2018-10-30 22:12
Thanks for catching this @kuhnchris!

**Comment by jasonrhaas** [comment] 2018-10-31 15:40
We discussed this a little bit in Slack.  We decided that we don't want (and maybe can't prevent) people from sending Kudos to themselves.  However, we can categorize them differently in the profile for reputation purposes.  Maybe adding a tab called "My Collected Kudos", or something like that.  Alternatively we could highlight the Kudos that were sent to the user at the top of the profile, driving home the reputation aspect.

**Comment by kuhnchris** [comment] 2018-10-31 16:04
How about a split between "Bought Kudos" and "Received Kudos" ? (And a tab "All my Kudos")

**Comment by mbeacom** [comment] 2018-11-01 13:51
User is now alerted with a warning message when sending a Kudos to their own handle via: https://github.com/gitcoinco/web/commit/83f4516e563b938e610482cd4beaee3555bf0546 from @owocki - Closing this for now as this is not a bug, but intended behavior.  We can raise a new issue to track possibly including a sort for self-awarded kudos.

**Closed by mbeacom** 2018-11-01 13:51 UTC
Labels: Gitcoin Kudos, bug, priority: ungroomed
