### ISSUE TITLE
Verify Grant Issue

### ISSUE THREAD

**Issue by DaWe35** [gitcoinco/web#7431] opened 2020-09-16 14:47 UTC
### Who
https://twitter.com/CoolHDstudio
Verify post: https://twitter.com/CoolHDstudio/status/1306242632943833088
### What 
https://gitcoin.co/grants/1156/skylive-decentralized-live-streams-videos
### Why
Verify button does not work :( Thank you!

**Comment by owocki** [comment] 2020-09-16 21:18
i think the issue is you have  https://twitter.com/CoolHDstudio listed as your twitter not @CoolHDstudio ; @zoek1 can we make the system smart enough to handle links instead of just usernames

**Comment by DaWe35** [comment] 2020-09-16 21:22
Ahh thanks, verification passed!

**Comment by willsputra** [comment] 2020-09-18 14:02
awesome! closing this :)

**Closed by willsputra** 2020-09-18 14:02 UTC
Labels: Grants/Verification
