### ISSUE TITLE
Payment reminder not working

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#6571] opened 2020-05-04 11:59 UTC
from @vporton 

When I try to Send Payment Reminder for https://gitcoin.co/issue/gitcoinco/web/6448/4216 I get: "got an error. please try again, or contact support@gitcoin.co"

**Comment by vporton** [comment] 2020-05-04 15:46
Duplicate of #6568

**Closed** 2020-12-16 14:52 UTC
