### ISSUE TITLE
Error executing transaction

### ISSUE THREAD

**Issue by abitrolly** [gitcoinco/web#220] opened 2018-01-06 20:42 UTC
##### Description
I tried to fund issue with this transaction - https://etherscan.io/tx/0x09cae8ee3bc8da2f543e5990444d3ef9e02c5b5a9c4b523176d1999d8c276563 I didn't close the window, but left the tab for like half an hour. As you may see, the transaction got mined, but interface contained this error message about executing transaction.

So, the transaction is there, but web interface has no data. Might be similar to #128

I expected backend to detect transaction anyway, because information is there. There should be a way to match all sent transactions to smart contract address that are not present in backend DB.

**Comment by owocki** [comment] 2018-01-10 01:16
sorry about that @abitrolly -- i just went in and processed it manually..

root cause fix for this is at https://github.com/gitcoinco/web/issues/128

**Closed by owocki** 2018-01-10 01:16 UTC

**Comment by abitrolly** [comment] 2018-01-10 08:40
No need to be sorry. We need to close #128. :)
