### ISSUE TITLE
Coop Bounty - 1 Start Work Missing

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1678] opened 2018-07-10 15:39 UTC
from Tim Vanmourik

https://github.com/TimVanMourik/GiraffeTools/issues/72

A coop bounty, and two applications. However, the second one (@Thoughtscript) doesn't show up in the list, and the first one twice.

![image 10](https://user-images.githubusercontent.com/238235/42521029-cb4ccc04-8435-11e8-886d-582d212b7f27.png)

**Comment by owocki** [comment] 2018-07-10 16:11
@pinkiebell is this something we missed in the last PR?

happy to tip out something extra if you can find a fix

**Comment by pinkiebell** [comment] 2018-07-10 16:45
@owocki I will take a look

**Comment by pinkiebell** [comment] 2018-07-10 16:54
@owocki can you trigger create_activity_records? Thanks

**Comment by pinkiebell** [comment] 2018-07-10 18:37
My guess: User's network connection was reset/other error after clicking on start work - modal dialog.
After that we update the ui and display a green success banner instead of an error.

**Comment by owocki** [comment] 2018-07-10 19:56
the application to start work went through, but not the `Activity` object.. so I dont think it was a network issue

**Comment by pinkiebell** [comment] 2018-07-10 21:16
@owocki 

Hmm. Then the user should be in 'bounty.interests' ? (looking at create_new_interest_helper)

https://gitcoin.co/actions/api/v0.1/bounties/?github_url=https://github.com/TimVanMourik/GiraffeTools/issues/72&network=mainnet&standard_bounties_id=724

**Comment by pinkiebell** [comment] 2018-07-10 21:55
Ohh wait. Maybe the second application @TimVanMourik means is a duplicate email from the first applicant?

**Comment by TimVanMourik** [comment] 2018-07-11 07:08
Hi @pinkiebell, sorry, my bug report wasn’t very elaborate. The timeline of the problem was this:
1. @Weezyana07 applied, I received an email and I approved him
2. @Thoughtscript applied (“@TimVanMourik - Signed up! Thanks!”). I did not receive any email. I checked out the page and saw screenshot above: a duplicate of @Weezyana07, although I could not approve him.
3. You, @pinkiebell,  applied as a test, I did receive the email and the gitcoin message was updated accordingly. I did not check out the bounty page to see if I could confirm you before you removed your application.

**Comment by pinkiebell** [comment] 2018-07-11 07:20
@TimVanMourik 

Thanks!  'Weezyana07 Applied' & 'Worker Weezyana07, Approved'  are two different events, so that is fine.

That means @Thoughtscript has not applied or he tried and had a network error and got no error message; which means he just has to hit 'Start Work' again ;).

I think the issue is closed then? @owocki

**Comment by TimVanMourik** [comment] 2018-07-11 07:41
Ahhh, I was under the impression it was a ‘worker list’ instead of an ‘action list’! That in combination with @Thoughtscript not appearing lead me to this bug report. Problem resolved then! Thanks @pinkiebell

**Closed** 2018-07-19 06:20 UTC
