### ISSUE TITLE
Settings Bug - "<User: super-oleg>" needs to have a value for field "id" before this many-to-many relationship can be used.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#3984] opened 2019-03-18 15:31 UTC
"<User: super-oleg>" needs to have a value for field "id" before this many-to-many relationship can be used.

```
IntegrityError: update or delete on table "dashboard_profile" violates foreign key constraint "avatar_baseavatar_profile_id_6627af6c_fk_dashboard_profile_id" on table "avatar_baseavatar_"
DETAIL:  Key (id)=(9296) is still referenced from table "avatar_baseavatar_".

  File "django/db/backends/base/base.py", line 239, in _commit
    return self.connection.commit()
IntegrityError: update or delete on table "dashboard_profile" violates foreign key constraint "avatar_baseavatar_profile_id_6627af6c_fk_dashboard_profile_id" on table "avatar_baseavatar_"
DETAIL:  Key (id)=(9296) is still referenced from table "avatar_baseavatar_".

  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "marketing/views.py", line 556, in account_settings
    profile.delete()
  File "django/db/models/base.py", line 880, in delete
    return collector.delete()
  File "django/db/models/deletion.py", line 306, in delete
    sender=model, instance=obj, using=self.using
  File "cacheops/transaction.py", line 82, in __exit__
    self._no_monkey.__exit__(self, exc_type, exc_value, traceback)
  File "django/db/transaction.py", line 212, in __exit__
    connection.commit()
  File "django/db/backends/base/base.py", line 261, in commit
    self._commit()
  File "django/db/backends/base/base.py", line 239, in _commit
    return self.connection.commit()
  File "django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "django/db/backends/base/base.py", line 239, in _commit
    return self.connection.commit()
ValueError: "<User: super-oleg>" needs to have a value for field "id" before this many-to-many relationship can be used.
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "django/core/handlers/exception.py", line 100, in response_for_exception
    response = response.render()
  File "django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "app/context.py", line 91, in preprocess
    'is_moderator': profile.is_moderator if profile else False,
  File "dashboard/models.py", line 2013, in is_moderator
    return self.user.groups.filter(name='Moderators').exists() if self.user else False
  File "django/db/models/fields/related_descriptors.py", line 526, in __get__
    return self.related_manager_cls(instance)
  File "django/db/models/fields/related_descriptors.py", line 823, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<User: super-oleg>" needs to have a value for field "id" before this many-to-many relationship can be used.
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "django/core/handlers/exception.py", line 100, in response_for_exception
    response = response.render()
  File "django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "app/context.py", line 91, in preprocess
    'is_moderator': profile.is_moderator if profile else False,
  File "dashboard/models.py", line 2013, in is_moderator
    return self.user.groups.filter(name='Moderators').exists() if self.user else False
  File "django/db/models/fields/related_descriptors.py", line 526, in __get__
    return self.related_manager_cls(instance)
  File "django/db/models/fields/related_descriptors.py", line 823, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<User: super-oleg>" needs to have a value for field "id" before this many-to-many relationship can be used.
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "django/core/handlers/exception.py", line 100, in response_for_exception
    response = response.render()
  File "django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "app/context.py", line 91, in preprocess
    'is_moderator': profile.is_moderator if profile else False,
  File "dashboard/models.py", line 2013, in is_moderator
    return self.user.groups.filter(name='Moderators').exists() if self.user else False
  File "django/db/models/fields/related_descriptors.py", line 526, in __get__
    return self.related_manager_cls(instance)
  File "django/db/models/fields/related_descriptors.py", line 823, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<User: super-oleg>" needs to have a value for field "id" before this many-to-many relationship can be used.
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "django/core/handlers/exception.py", line 100, in response_for_exception
    response = response.render()
  File "django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "app/context.py", line 91, in preprocess
    'is_moderator': profile.is_moderator if profile else False,
  File "dashboard/models.py", line 2013, in is_moderator
    return self.user.groups.filter(name='Moderators').exists() if self.user else False
  File "django/db/models/fields/related_descriptors.py", line 526, in __get__
    return self.related_manager_cls(instance)
  File "django/db/models/fields/related_descriptors.py", line 823, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<User: super-oleg>" needs to have a value for field "id" before this many-to-many relationship can be used.
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "django/core/handlers/exception.py", line 100, in response_for_exception
    response = response.render()
  File "django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "app/context.py", line 91, in preprocess
    'is_moderator': profile.is_moderator if profile else False,
  File "dashboard/models.py", line 2013, in is_moderator
    return self.user.groups.filter(name='Moderators').exists() if self.user else False
  File "django/db/models/fields/related_descriptors.py", line 526, in __get__
    return self.related_manager_cls(instance)
  File "django/db/models/fields/related_descriptors.py", line 823, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<User: super-oleg>" needs to have a value for field "id" before this many-to-many relationship can be used.
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "django/core/handlers/exception.py", line 100, in response_for_exception
    response = response.render()
  File "django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "app/context.py", line 91, in preprocess
    'is_moderator': profile.is_moderator if profile else False,
  File "dashboard/models.py", line 2013, in is_moderator
    return self.user.groups.filter(name='Moderators').exists() if self.user else False
  File "django/db/models/fields/related_descriptors.py", line 526, in __get__
    return self.related_manager_cls(instance)
  File "django/db/models/fields/related_descriptors.py", line 823, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<User: super-oleg>" needs to have a value for field "id" before this many-to-many relationship can be used.
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "django/core/handlers/exception.py", line 100, in response_for_exception
    response = response.render()
  File "django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "app/context.py", line 91, in preprocess
    'is_moderator': profile.is_moderator if profile else False,
  File "dashboard/models.py", line 2013, in is_moderator
    return self.user.groups.filter(name='Moderators').exists() if self.user else False
  File "django/db/models/fields/related_descriptors.py", line 526, in __get__
    return self.related_manager_cls(instance)
  File "django/db/models/fields/related_descriptors.py", line 823, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<User: super-oleg>" needs to have a value for field "id" before this many-to-many relationship can be used.
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "django/core/handlers/exception.py", line 100, in response_for_exception
    response = response.render()
  File "django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "app/context.py", line 91, in preprocess
    'is_moderator': profile.is_moderator if profile else False,
  File "dashboard/models.py", line 2013, in is_moderator
    return self.user.groups.filter(name='Moderators').exists() if self.user else False
  File "django/db/models/fields/related_descriptors.py", line 526, in __get__
    return self.related_manager_cls(instance)
  File "django/db/models/fields/related_descriptors.py", line 823, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<User: super-oleg>" needs to have a value for field "id" before this many-to-many relationship can be used.
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "django/core/handlers/exception.py", line 100, in response_for_exception
    response = response.render()
  File "django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "app/context.py", line 91, in preprocess
    'is_moderator': profile.is_moderator if profile else False,
  File "dashboard/models.py", line 2013, in is_moderator
    return self.user.groups.filter(name='Moderators').exists() if self.user else False
  File "django/db/models/fields/related_descriptors.py", line 526, in __get__
    return self.related_manager_cls(instance)
  File "django/db/models/fields/related_descriptors.py", line 823, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<User: super-oleg>" needs to have a value for field "id" before this many-to-many relationship can be used.
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "django/core/handlers/exception.py", line 100, in response_for_exception
    response = response.render()
  File "django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "app/context.py", line 91, in preprocess
    'is_moderator': profile.is_moderator if profile else False,
  File "dashboard/models.py", line 2013, in is_moderator
    return self.user.groups.filter(name='Moderators').exists() if self.user else False
  File "django/db/models/fields/related_descriptors.py", line 526, in __get__
    return self.related_manager_cls(instance)
  File "django/db/models/fields/related_descriptors.py", line 823, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<User: super-oleg>" needs to have a value for field "id" before this many-to-many relationship can be used.
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "django/core/handlers/exception.py", line 100, in response_for_exception
    response = response.render()
  File "django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "app/context.py", line 91, in preprocess
    'is_moderator': profile.is_moderator if profile else False,
  File "dashboard/models.py", line 2013, in is_moderator
    return self.user.groups.filter(name='Moderators').exists() if self.user else False
  File "django/db/models/fields/related_descriptors.py", line 526, in __get__
    return self.related_manager_cls(instance)
  File "django/db/models/fields/related_descriptors.py", line 823, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<User: super-oleg>" needs to have a value for field "id" before this many-to-many relationship can be used.
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "app/middleware.py", line 15, in middleware
    response = get_response(request)
  File "django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "django/core/handlers/exception.py", line 100, in response_for_exception
    response = response.render()
  File "django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "app/context.py", line 91, in preprocess
    'is_moderator': profile.is_moderator if profile else False,
  File "dashboard/models.py", line 2013, in is_moderator
    return self.user.groups.filter(name='Moderators').exists() if self.user else False
  File "django/db/models/fields/related_descriptors.py", line 526, in __get__
    return self.related_manager_cls(instance)
  File "django/db/models/fields/related_descriptors.py", line 823, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<User: super-oleg>" needs to have a value for field "id" before this many-to-many relationship can be used.
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "django/core/handlers/exception.py", line 100, in response_for_exception
    response = response.render()
  File "django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "app/context.py", line 91, in preprocess
    'is_moderator': profile.is_moderator if profile else False,
  File "dashboard/models.py", line 2013, in is_moderator
    return self.user.groups.filter(name='Moderators').exists() if self.user else False
  File "django/db/models/fields/related_descriptors.py", line 526, in __get__
    return self.related_manager_cls(instance)
  File "django/db/models/fields/related_descriptors.py", line 823, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<User: super-oleg>" needs to have a value for field "id" before this many-to-many relationship can be used.
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "django/core/handlers/exception.py", line 100, in response_for_exception
    response = response.render()
  File "django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "app/context.py", line 91, in preprocess
    'is_moderator': profile.is_moderator if profile else False,
  File "dashboard/models.py", line 2013, in is_moderator
    return self.user.groups.filter(name='Moderators').exists() if self.user else False
  File "django/db/models/fields/related_descriptors.py", line 526, in __get__
    return self.related_manager_cls(instance)
  File "django/db/models/fields/related_descriptors.py", line 823, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<User: super-oleg>" needs to have a value for field "id" before this many-to-many relationship can be used.
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "django/core/handlers/exception.py", line 100, in response_for_exception
    response = response.render()
  File "django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "app/context.py", line 91, in preprocess
    'is_moderator': profile.is_moderator if profile else False,
  File "dashboard/models.py", line 2013, in is_moderator
    return self.user.groups.filter(name='Moderators').exists() if self.user else False
  File "django/db/models/fields/related_descriptors.py", line 526, in __get__
    return self.related_manager_cls(instance)
  File "django/db/models/fields/related_descriptors.py", line 823, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<User: super-oleg>" needs to have a value for field "id" before this many-to-many relationship can be used.
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "django/core/handlers/exception.py", line 100, in response_for_exception
    response = response.render()
  File "django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "app/context.py", line 91, in preprocess
    'is_moderator': profile.is_moderator if profile else False,
  File "dashboard/models.py", line 2013, in is_moderator
    return self.user.groups.filter(name='Moderators').exists() if self.user else False
  File "django/db/models/fields/related_descriptors.py", line 526, in __get__
    return self.related_manager_cls(instance)
  File "django/db/models/fields/related_descriptors.py", line 823, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<User: super-oleg>" needs to have a value for field "id" before this many-to-many relationship can be used.
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "django/core/handlers/exception.py", line 100, in response_for_exception
    response = response.render()
  File "django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "app/context.py", line 91, in preprocess
    'is_moderator': profile.is_moderator if profile else False,
  File "dashboard/models.py", line 2013, in is_moderator
    return self.user.groups.filter(name='Moderators').exists() if self.user else False
  File "django/db/models/fields/related_descriptors.py", line 526, in __get__
    return self.related_manager_cls(instance)
  File "django/db/models/fields/related_descriptors.py", line 823, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<User: super-oleg>" needs to have a value for field "id" before this many-to-many relationship can be used.
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 91, in __call__
    response = response or self.get_response(request)
  File "django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "django/core/handlers/exception.py", line 100, in response_for_exception
    response = response.render()
  File "django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "django/template/base.py", line 169, in render
    with context.bind_template(self):
  File "python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "django/template/context.py", line 246, in bind_template
    updates.update(processor(self.request))
  File "app/context.py", line 91, in preprocess
    'is_moderator': profile.is_moderator if profile else False,
  File "dashboard/models.py", line 2013, in is_moderator
    return self.user.groups.filter(name='Moderators').exists() if self.user else False
  File "django/db/models/fields/related_descriptors.py", line 526, in __get__
    return self.related_manager_cls(instance)
  File "django/db/models/fields/related_descriptors.py", line 823, in __init__
    (instance, self.pk_field_names[self.source_field_name]))

```

**Comment by rafalkowalski** [comment] 2019-03-18 16:18
@owocki i can work on it

**Comment by owocki** [comment] 2019-03-18 16:40
great!

**Comment by rafalkowalski** [comment] 2019-03-18 17:40
@owocki Could you book this issue for me?

**Comment by owocki** [comment] 2019-03-18 21:53
sorry what does "book this issue" mean

**Comment by rafalkowalski** [comment] 2019-03-18 21:55
At the top you can set assignment person.

**Comment by owocki** [comment] 2019-03-18 22:58
hmm for some reason i can't seem to assign you http://bits.owocki.com/72434598f879/Screen%20Shot%202019-03-18%20at%204.57.54%20PM.png

**Comment by rafalkowalski** [comment] 2019-03-18 23:00
Ah ok, I thought that everyone could be assigned to an issue. Probably it's releated that I'm not a member of organization.

**Comment by thelostone-mc** [comment] 2019-03-19 04:16
@rafalkowalski yeah issues can be assigned only to members of the repo!
Go ahead and work on it ! It's yours for the taking ^_^

**Comment by rafalkowalski** [comment] 2019-03-19 21:29
@thelostone-mc  I'm not able to reproduce above bug in test environment ;/

**Comment by thelostone-mc** [comment] 2019-03-23 10:16
@owocki I'm not able to reproduce this locally ! mind sharing the steps ?

**Closed** 2020-06-02 11:23 UTC
Labels: backend, cannot reproduce, community member
