### ISSUE TITLE
Shared Payment Milestone III - As a funder I'd like to be able to co manage payment and permission with my team.

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#5021] opened 2019-08-15 20:50 UTC
### User Story

As a funder I'd like to have a way to represent my organization and what it's all about.

### Why

Milestone III
- Adds the ability to create, edit, payout, etc. a StandardBounties V2 contract without any changes in UI or end-user experience. Simply put, the current functionality works as expected, except the underlying smart contract has been upgraded. The data synced from Github is used when the smart contract is created to add the funder's team members as either "Issuers" or "Approvers" within the smart contract so that future milestones work retroactively with bounties created after these changes are live.

Story Points: 13
UX/UI work: none

### Assumptions
Human - 
Business - 
Tech -

**Comment by danlipert** [comment] 2019-08-23 14:18
This is a duplicate of https://github.com/gitcoinco/web/issues/5022 right?

**Closed** 2019-08-23 14:18 UTC
Labels: Sprint 17
