### ISSUE TITLE
Incorrect Funding Time Period Shown on Issue Details

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1774] opened 2018-07-17 14:25 UTC
**Describe the bug**
Funded Issue from last night shows wrong time for when the issue was opened.

**To Reproduce**
[comment]: # (Steps to reproduce the behavior)

- Display time is wrong when an issue is posted

**Expected behavior**
[comment]: # (A clear and concise description of what you expected to happen.)

- [ ] Show the correct time listed on issue details

**Screenshots**

<img width="1210" alt="screen shot 2018-07-17 at 10 23 01 am" src="https://user-images.githubusercontent.com/238235/42823468-9ee655ba-89ab-11e8-8167-ea960b55cfae.png">

**Desktop (please complete the following information):**

- OS: Mac
- Browser Chrome

**Comment by thelostone-mc** [comment] 2018-07-19 08:30
@PixelantDesign not able to reproduce this!
Can you check if this still happening  ?

**Comment by PixelantDesign** [comment] 2018-07-19 12:55
I haven't had this issue since...  @mbeacom  has some context on when this happened, are there specific things that @thelostone-mc should be checking for @mbeacom?

**Comment by thelostone-mc** [comment] 2018-08-10 20:17
Closing as this cannot be reproduced!

**Closed by thelostone-mc** 2018-08-10 20:17 UTC
Labels: bug
