### ISSUE TITLE
round 8 bug / improve list

### ISSUE THREAD

**Issue by thelostone-mc** [gitcoinco/web#7947] opened 2020-11-26 17:27 UTC
**MAJOR**
- [x] checkIsCurator function is broken as the logic doesn't fit the data (map collections array and check curators on each one). 
- [x] removeCollection doesn't work not id is found.
- [x] fix to 2 decimals  [in prediction curve UI](https://user-images.githubusercontent.com/5358146/100424743-07521b00-30b4-11eb-9500-70394c730490.png) **FIX: 913db656f**
- [x] make background image in RoutingPolicy as optional **FIX: fc9b24a9c**
- [x] add new field name in RoutingPolicy to make it easier to identify **FIX: fc0c8bd54**
- [x] in UI customer-name is not appended to URL [image](https://user-images.githubusercontent.com/5358146/100439252-4fc80380-30c9-11eb-9003-58cf8e75886d.png) **FIX: 76ff4383d**
- [x] CLR banner not being updating in UI despite setting image in GrantCLR.logo **FIX: 97370ea7f**
- [x] Appending `/` URL to endpoint should not return 404 **FIX: 5e56dff43**
- [x] If grant is part of multiple rounds -> the round names are not appended
- [x] made CLR banners into accordion so that it is collapsible and store that boolean in local-storage
- [x] edit grant broken. **FIX: 7547b5fbf**

**MINOR**
- [x] ensure error are cleared after submitting a match pledge  **FIX: c7767fc63**
- [x] fix broken collections UI  **FIX: 821de8c9c** 
- [ ] fix alignment in prediction curve UI [image](https://user-images.githubusercontent.com/5358146/100424503-b3dfcd00-30b3-11eb-95d2-8c709af765a6.png)
- [x] Show My Items on landing only if user is logged in **FIX: 1b33dcdfe**
- [x] update text in [Did you know section](https://user-images.githubusercontent.com/5358146/100425472-4765cd80-30b5-11eb-87bf-853f4df621f9.png) **FIX: fe0b6f11c**
- [x] Show `Add to collection` in card only if user is logged in and has a collection of their own [image](https://user-images.githubusercontent.com/5358146/100426793-7715d500-30b7-11eb-9a64-a6aba5676ace.png)
- [x] Sidebar should auto-close after canceling grant
- [x] Remove Current & Past Sponsors in UI **FIX: 42c4d73ab**
- [x] Hide prediction curve when a grant is not part of a CLR **FIX: ad530e813**
- [x] related grants styles

**Comment by owocki** [comment] 2020-11-27 15:40
just tested, feels pretty rough.  here are my QA notes (all in latest chrome + metamask):

# showstoppers

- when i try to edit a grant i get this error https://bits.owocki.com/jkuYqY4y  error in console is error: grant creation failed with status: 400 and message: error: zcash_payout_address must be a transparent address
- CANCEL GRANT does not seem to work.  when i type in CONFIRM in the alert bar, nothing happens.  nothing to let me know if my grant was actually canceled or not.
- cannot create a grant.  it just says 'verify form errors' when there are no actual form errors https://bits.owocki.com/DOuogor5 - i think this happened when i had a validation issue but then fixed it.  i could never get past validation again without refreshing page.
- on zksync checkout, i was taking to a new page checkout.zksync.com which had the following issues 
1. on my grants page, i see this error after going to zksync https://bits.owocki.com/z8u454jZ - looks related to this https://bits.owocki.com/YEuQKQxX
2. i am never taken to the 'success, you checked out, tweet about it now!' modal after checkout
- on standard checkout, i sign this message ( https://bits.owocki.com/qGulylkk ) and then nothing happens.  maybe related to this JSON error again? https://bits.owocki.com/4guOzO6E
- i cant actually test the 'new matching partner' stuff bc no collections or categories show up ( https://bits.owocki.com/2Nu0xE25 & https://bits.owocki.com/RBu974Pp )

# major 
- 'add to cart' should not be the default action for the collections list view https://bits.owocki.com/xQuYZnK9 , it should be 'view collection'
- banner is not updated up top (even if i upload one in the admin i get this https://bits.owocki.com/2Nu0x05X)
- http://localhost:8000/_administrationgrants/grantclr/add takes forever to load - probably needs a raw_id field on the `owner` field
- related grants is empty when first clicked ( https://bits.owocki.com/xQuYZY4x ) - then takes about 15 seconds to load when it finally does
- whats the deal with the grants clr banner here ? https://bits.owocki.com/6quxkxeD  its completely white
- can we remove 'add all to cart' from the collection view page pls? https://bits.owocki.com/xQuYZYYA
- on grant creation, why are we forcing people to add an `@` symbol? seems like needless uesr work, we can just add it on the backend if needed.  dont introduce unnecessary friction pls https://bits.owocki.com/qGulylqy
- total on my cart is wrong.  4x1 DAI = 4 DAI, not 1 DAI https://bits.owocki.com/12uK5KbX

# attention to detail stuff
- i dont see the 'show idle grants' filter on the left hand side of the nav anymore.  are we not filtering out idle grants anymore?  if so, why not?  that wasnt a requirement.
- 'become a matching partner' is lopsided https://bits.owocki.com/2Nu0xjZy
- the page refreshes as i click around the nav; i thought we were fixing that this round?
- if i remove my grant from cart on the side cart the 'remove from cart' button does not change on the UI https://bits.owocki.com/qGulyvWn
- itd be nice if i could click/unclick this label to check/uncheck the box https://bits.owocki.com/mXu5j5Wl
- the 'back to grants' breadcrumb that used to be consistent across each grant page + cart is no longer on the grant detail page https://bits.owocki.com/p9urlrvN
- i setup an 'infra tech' round and made it active and ran 'create_page_cache', but it never showed up on the left navbar as a round https://bits.owocki.com/6quxkQmO
- follow button on grant detail page does nothing if youre logged out (we should tell the user they should login first)

# could not test
- i could not test many of the trustbonus items, due to lack of setup on some of them, and lack ofa ctually having those services on others.  will need to make sure its well tested elsewhere.
- a grant being in multiple CLR rounds at once
- emails - never got any
- videos - where do i add a video to my grant? i wasnt compelled to in any place?
- self service matching partner stuff; i was blocked by the showerstopped issue above.
- does the 'last update' field actually update when the grant is edited, @octavioamu ? thatll be important

**Comment by octavioamu** [comment] 2020-11-28 00:13
> on grant creation, why are we forcing people to add an @ symbol? seems like needless user work, we can just add it on the backend if needed. don't introduce unnecessary friction pls

I added better validation for this but extract the username of any format seems overkill to me. I was looking on some of the possible patterns https://regex101.com/r/s6JoZ5/3

**Comment by owocki** [comment] 2020-11-28 03:54
testing latest build

cannot add to cart on the grants/clr page ( http://localhost:8000/grants/clr/ethereum/7/MATIC/? )

i pulled the latest origin/grants-round-8 and i still can’t checkout on it.. this is what i get
https://bits.owocki.com/qGulyqe9

why do twiter handles require @ signs all of a sudden?  feels like something we can enforce on the backend, instead of adding validation thats cumbersome to the user.

**Comment by thelostone-mc** [comment] 2020-11-28 10:59
@chibie could you take a look at the twitter handle !
let's make it such that it auto adds an @ if it's not present when frontend sends it to the backend ?

**Comment by zoek1** [comment] 2020-11-30 08:29
@owocki I managed the twitter handle in the PR #7962

**Comment by zoek1** [comment] 2020-11-30 08:31
Also I'm still getting the error: zcash_payout_address must be a transparent address when i try to edit any grant, the fix isn't merged yet?

**Comment by thelostone-mc** [comment] 2020-11-30 10:36
@zoek1 could you make sure your grant has 
- zcash_payout_address has value '0x0'
- admin_address has a valid ETH address ?

**Comment by owocki** [comment] 2020-11-30 14:49
> I added better validation for this but extract the username of any format seems overkill to me.

i just dont want the grant creation form to fail validation bc of the lack of an `@` symbol.  seems this could be accomplished by just doing an alphanumeric regex.  if we want to ensure consistence on the backend, the @ symbol can be added on hte backend.

more testing notes:

1. after i add a grant to cart on grant detila page, the side cart no longer shows.  where do i go to checkout?
1. when i create a grant contribution on the frontend, i dont see anything in the DB
	(i wanted to test to make sure that when i check 'include this in CLR' it actually stores that state in the DB)
1. i can't seem to test a grant being in multiple CLRs bc i can't make a contribution + get it to store in the DB...   it'd be good to know someone has tested this

**Comment by octavioamu** [comment] 2020-11-30 23:00
>after i add a grant to cart on grant detila page, the side cart no longer shows. where do i go to checkout?
I just pushed a commit adding the sidecart back

**Comment by apbendi** [comment] 2020-12-01 03:55
Twitter verification on the Trust Bonus tab is broken in the grants branch, as far as I can tell. Seems like the regression came from this PR, which I commented on with a bit more context: https://github.com/gitcoinco/web/pull/7962

@zoek1, can you expand on why you were modifying the twitter verification endpoint? That endpoint is used for the Trust Bonus. Was it your intention to change the behavior of the Trust Bonus?

**Comment by apbendi** [comment] 2020-12-01 03:59
Attempting to test SMS verification from the Trust Bonus tab gives the following error from the backend:

```
, uri, response, 'Unable to fetch record')
web_1            | twilio.base.exceptions.TwilioRestException:
web_1            | HTTP Error Your request was:
web_1            |
web_1            | GET /PhoneNumbers/+1610-733-9707
web_1            |
web_1            | Twilio returned the following information:
web_1            |
web_1            | Unable to fetch record: Authenticate
web_1            |
web_1            | More information may be available here:
web_1            |
web_1            | https://www.twilio.com/docs/errors/20003
chat_1           | {"level":"info","ts":1606794986.5376687,"caller":"sqlstore/supplier.go:212","msg":"Pinging SQL","database":"master"}
db_1             | 2020-12-01 03:56:26.542 UTC [701] FATAL:  database "chat" does not exist
chat_1           | {"level":"error","ts":1606794986.5437012,"caller":"sqlstore/supplier.go:224","msg":"Failed to ping DB","error":"pq: database \"chat\" does not exist","retrying in seconds":10}
```

Has our API key or auth token changed? (Reminder not to post these here)

**Comment by apbendi** [comment] 2020-12-01 04:24
Need a bit more direction on how to regression test Google Verification: https://github.com/gitcoinco/web/pull/7631#issuecomment-736207735

Should still be working but would like to test locally

**Comment by zoek1** [comment] 2020-12-01 06:27
@apbendi my intention wasn't to modify the trust bonus, just the twitter grant verification. The error is due to wrong conditional statement. The fix for that is here https://github.com/gitcoinco/web/pull/7974

**Comment by danlipert** [comment] 2020-12-01 10:22
Editing an ETH grant now throws an error when trying to save. The error displays in the UI and in the console the error is: `_detail-component.js:99 error: grant edit failed with status: 400 and message: error: zcash_payout_address must be a transparent address`
Seems that for ETH grants we are trying to validate their zcash address which doesn't apply here.

**Comment by danlipert** [comment] 2020-12-01 10:24
When creating a grant, the validation fails if the twitter username does not start with an "@" symbol. While I appreciate the attention to detail to validate the twitter handle starting with @, its bad UX as the placeholder text shows a username without the @ symbol.

**Comment by danlipert** [comment] 2020-12-01 11:04
While checking out with multiple ETH grants in my cart via zksync, I received an error alert in the UI while I was redirected to the zksync checkout. Zksync checkout worked perfectly as expected, and when finished I was returned to the grants page and received the success modal, but during this time if I return to the cart page the alert is shown which reads "Insufficient balance to complete checkout". I don't know if this refers to the zksync balance being insufficient as I a) did have enough funds in my wallet to complete checkout and b) did not have any L2 funds at this time, but either way if that is "expected behavior" its definitely confusing/scary for users and the copy and alert style need to be changed.

![Screen Shot 2020-12-01 at 7 56 54 PM](https://user-images.githubusercontent.com/869266/100732625-54195700-3410-11eb-8f73-24c4506c6048.png)

**Comment by thelostone-mc** [comment] 2020-12-01 11:53
^ @mds1

**Comment by mds1** [comment] 2020-12-01 14:10
Hey @danlipert. The insufficient balance modal should only show if you have insufficient funds in both L1 and L2. Can you clarify the steps to reproduce? I'm not sure I follow. 

> but during this time if I return to the cart page the alert is shown which reads "Insufficient balance to complete checkout"

This is the main part I'm confused on. The success modal redirects you off the cart page, so did you then go back the cart, and the cart was not cleared? Or did you add new grants to your cart after? Or something else?

Also, what was in your cart at the time of that second checkout? It looks like you may have had an empty "amount" field based on the console error messages showing `vaule=""`

**Comment by danlipert** [comment] 2020-12-01 15:13
@mds1 I had sufficient funds in L1 but not L2. Not sure exactly how to reproduce. What happened was the zksync flow opened in a new tab, and i went back to the cart tab just to check and the error was there while I was going through the zksync flow. Once I finished the zksync flow I was redirected back to the success modal screen. I took the screenshot while I was going through the zksync flow. I'm pretty sure all the amount fields had something in them as I got the appropriate number of txns in the zksync checkout explorer link list, but they were all very small amounts.

**Comment by mds1** [comment] 2020-12-01 15:20
@danlipert Ahhh I see, got it, thanks for the additional info! I'll look into this today

**Comment by willsputra** [comment] 2020-12-01 16:03
Browser: Brave Mac 1.17.73

**Major**

- [ ] zkSync Checkout: Tried contributing 0.5 DAI to two grants with optional tip, got a "Transactions batch summary fee is too low" error [tx](https://user-images.githubusercontent.com/19514207/100763566-4a9fe700-3430-11eb-86f1-091de35ff8e2.png) |  [error](https://user-images.githubusercontent.com/19514207/100763555-4673c980-3430-11eb-9f65-a8b47bcdecb2.png) @mds1 
- [ ] Grant Contribution Success Email: I contributed 0.5 DAI but email shows 1.0000 SAI [contrib](https://user-images.githubusercontent.com/19514207/100764357-36101e80-3431-11eb-8ff2-003530388364.png) | [email](https://user-images.githubusercontent.com/19514207/100764463-50e29300-3431-11eb-9514-ee5904cfe04f.png)


**Minor**

- [ ] Quick View: Wall of Love numbers scroll down as you scroll down. [screenshot](https://user-images.githubusercontent.com/19514207/100762301-c731c600-342e-11eb-89d6-7a838b73a551.png)
- [ ] Grant Detail: Description font is different [screenshot](https://user-images.githubusercontent.com/19514207/100762735-4f17d000-342f-11eb-92d7-a2ffc493711d.png)
- [ ] zkSync Checkout: Are "Grants Round 8+ Dev Fund" and "Grants Round 7+ Development Fund" different? Current optional tip goes to "Grants Round 7+ Development Fund" [screenshot](https://user-images.githubusercontent.com/19514207/100763285-ec730400-342f-11eb-80b2-1a39d536cba9.png)

**Comment by danlipert** [comment] 2020-12-01 16:08
Thanks @willsputra ! I also just got the SAI / DAI issue but only for one of the grants (gitcoin dev fund optional contribution) so probably has something to do with when the grant was created back when you could specify a specific type of token you accepted. I also received 4 emails for the 4 rolled up zksync contributions :/ But was able to successfully check out. @willsputra the error you got I believe has to do with the calculation of the zksync fee being larger than what you would have saved by using it or something like that.

- [ ] batch email not working, receiving separate emails per contrib

- [ ] gitcoin dev fund grant contribution email shows contributing 5 SAI when I actually contributed 0.15 DAI https://zkscan.io/transactions/sync-tx:484dd93f81ab2de7f2bd0da457b11bc8b8fdc6138d3dffb36495e94bde1801a3 
![Screen Shot 2020-12-02 at 1 08 19 AM](https://user-images.githubusercontent.com/869266/100765481-e171a100-343a-11eb-9f0c-827c817a43ed.png)

**Comment by octavioamu** [comment] 2020-12-01 16:10
[ ] related grants need pagination and layout

**Comment by owocki** [comment] 2020-12-01 16:10
i dont think the 'anonymize my contribution' is working. i just checked the box + made a contribution and it showed up in the feed/transaction list as being from me. ( https://bits.owocki.com/jkuYymEA ) it should show the gitcoinbot in those places instead (grants/tasks.py:182 is supposed to do this)

**Comment by owocki** [comment] 2020-12-01 16:55
i just got 8 emails from making 8 contributions in 1 cart.  is the bulk checkout email going to make it in?

**Comment by owocki** [comment] 2020-12-01 16:55
CSS looks messed up on banner cover image https://bits.owocki.com/jkuYyWPq

**Comment by owocki** [comment] 2020-12-01 18:21
- [ ] the responsive design on the banner looks really bad.  https://bits.owocki.com/04uNkRKG  

the banner should be < 300 px high on mobile, 400px on tablet, etc...

**Comment by mds1** [comment] 2020-12-01 18:30
> zkSync Checkout: Tried contributing 0.5 DAI to two grants with optional tip, got a "Transactions batch summary fee is too low" error tx | error @mds1

@willsputra I noticed this also and messaged the zkSync team about it a few hours ago. We haven't been able to figure out how to reliably introduce it, so their checking the server for bugs on their end. They're also updating the UI with two changes:
1. Show a minimum fee and recommended fee. Minimum is what may sometimes cause this bug. Recommended is ~1 cent higher and never will
2. If this error happens, prompt the user with a button to continue checkout (this will pull the updated correct fee from the server)

>  zkSync Checkout: Are "Grants Round 8+ Dev Fund" and "Grants Round 7+ Development Fund" different? Current optional tip goes to "Grants Round 7+ Development Fund" screenshot

Good catch. Let me get a PR in to fix this

**Comment by owocki** [comment] 2020-12-01 18:33
- [ ] on the collections view ( https://gitcoin.co/grants/collections?collection_id=2 )  we dont need to show all the diff grants rounds https://bits.owocki.com/jkuYy8xE

**Comment by octavioamu** [comment] 2020-12-01 18:40
- [ ] you can add a video on grant  edit but not on grant creation.

**Comment by octavioamu** [comment] 2020-12-01 18:44
how the banner should work for mobile? I can reduce but that banner doesn't seems to work for mobile.
![image](https://user-images.githubusercontent.com/1358093/100783049-0b4fa700-33ec-11eb-8851-80169d3457e7.png)

**Comment by owocki** [comment] 2020-12-01 18:45
- [ ] Related Grants takes about 15s to load on this grant https://gitcoin.co/grants/524/clrfund
- [ ] On the same grant, the h1 h2 h3 text looks funny bc it is larger than the grant title text ( screenshot: https://bits.owocki.com/BluQEvBn ) . it would be better if the grant desc h1 was always smaller than the grant title
- [ ] a bunch of grants in the dapp tech category say they are "not in an active CLR round" on the carts. screenshot: https://bits.owocki.com/o0uqxLEO - even though they are in the dapp tech category.
- [ ] this grant detail page takes 8s to load

```
kevinowocki@local /Users/kevinowocki~ % time curl https://gitcoin.co/grants/86/gitcoin-grants-round-8-dev-fund > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6605k  100 6605k    0     0   789k      0  0:00:08  0:00:08 --:--:-- 1657k
curl https://gitcoin.co/grants/86/gitcoin-grants-round-8-dev-fund > /dev/null  0.04s user 0.04s system 0% cpu 8.393 total
```
here is the trace for the same `https://bits.owocki.com/Z4uqzNAJ`

**Comment by octavioamu** [comment] 2020-12-01 18:46
- [ ] banner is 814px taking all the screen height making the experience bad @PixelantDesign

**Comment by owocki** [comment] 2020-12-01 18:46
@octavioamu i trust your judgement about how to resize the banner on mobile.   i agree with your comment about the need to make it larger than it is in your screenshot

**Comment by octavioamu** [comment] 2020-12-01 18:51
with the current banner design I don't see a way to fit it on a small screen more than showing the center or just making it small.

**Comment by owocki** [comment] 2020-12-01 18:59
- [ ] on the grant details page of https://gitcoin.co/grants/149/rotki-the-portfolio-tracker-and-accounting-tool-t  on this module  https://bits.owocki.com/L1uOYE77  (1) contributors is spelled wrong (2) it should show the amount raised this round + num contributors this round, not total round contributors. @octavioamu

**Comment by octavioamu** [comment] 2020-12-01 19:50
@owocki is using positive_round_contributor_count as the old one 🤔

**Comment by owocki** [comment] 2020-12-01 20:04
then why does it show 233 Contributiors for a round that started today

**Comment by octavioamu** [comment] 2020-12-01 20:07
seems the api is returning that 233 on positive_round_contributor_count https://gitcoin.co/grants/v1/api/grant/149/

**Comment by vs77bb** [comment] 2020-12-01 20:12
- [ ] adding comma's here, also design wise -- would it look better 2x3 stacked instead of 1x6?  

![image](https://user-images.githubusercontent.com/23297747/100791634-84003480-33e7-11eb-81c2-9f37337585ad.png)

**Comment by owocki** [comment] 2020-12-01 20:28
cb4b75f13a0e2a1169fb26fde3f2cd2336858448 fixes the positive contributor count issue

**Comment by corydickson** [comment] 2020-12-01 21:07
> i just got 8 emails from making 8 contributions in 1 cart. is the bulk checkout email going to make it in?
> 
> **aditya:** Doubtful ! Given that subscription creation happens in celery. I'm not sure how we'd be able to wait for all celery tasks to be processed and only then send an email ! scope lift is working on it -> but I'm not sure how we'd actually do this

I think I've resolved the issue with celery using chords see: https://github.com/corydickson/web/tree/cd-bulk-email-cart and https://docs.celeryproject.org/en/stable/reference/celery.html#celery.chord

Before we were passing around the subscription that was created in the task, and now there is a bug retrieving the correct subscription when that task is completed, particularly when a user contributes the same grant twice. When filtering for the correct object I'm using the grant and the contributor profile which is not enough to get the most recently created.  Hence the bug of improper balances being shown in the email.

**Comment by thelostone-mc** [comment] 2020-12-01 21:10
@corydickson well the unique identifier would be the pk of the subscription ! I'm not sure what else would qualify

**Comment by corydickson** [comment] 2020-12-01 21:17
@thelostone-mc yeah retrieving that from each task is difficult as if a single task fails then the email task will receive an empty array

**Comment by thelostone-mc** [comment] 2020-12-01 21:22
What you could do is make it into one celery task !
If you contribute to 5 grants -> fire one celery task -> loop through it there and let the code inside task run sync 
Once all subscriptions are created -> you can fire the bulk email. At that point -> you have access to subscriptions so you can pass those as well and get the email to fire aka no extra query

**Comment by apbendi** [comment] 2020-12-01 21:29
- [ ] Move Idena verification to an "Beta Testing" section on Trust Bonus
- [ ] Remove Idena verification from conditional that shows cart banner for Trust Bonus
- [ ] Remove the 25% matching reward for Idena

**Comment by corydickson** [comment] 2020-12-01 21:36
@thelostone-mc I. was hesitant to go in that direction in case one of the grants in the cart fails processing as it would block all other contributions from completing. There is also possibly a performance hit since we are no longer parallelizing tasks. If I understand your solution correctly, and you are comfortable with that trade off, I can start working in that direction.

**Comment by thelostone-mc** [comment] 2020-12-02 04:08
@corydickson well i think it's alright doing that cause

- the API response will still be quick to the end user
- other contributions being blocked cause of one failing -> we could wrap them out try catch and ignore that exception and continue to process the others
- performance hit will be on the celery worker which is alright -> we can afford to wait there


cc @danlipert

**Comment by danlipert** [comment] 2020-12-02 11:40
the performance hit is negligible - its async which is all that matters. Just make the task itself robust against the expected failure here with a try block. @corydickson @thelostone-mc

**Comment by vs77bb** [comment] 2020-12-02 14:39
🔵  scrolling bar on project descriptions are cutting off words, a bit more space on the right side would clean it up 

![image](https://user-images.githubusercontent.com/23297747/100886763-31c02180-3482-11eb-9df2-3e6f1a84f190.png)

**Comment by mds1** [comment] 2020-12-02 15:56
- [ ] Redirect not working properly if not logged in. Steps to reproduce:
1. Open a private tab
2. Add item to your cart
3. Click checkout
4. Login to GitHub
5. You are redirected to the home page / town square, and not your cart

**Comment by mds1** [comment] 2020-12-02 16:00
- [ ] If a wallet is not connected when loading the cart, the zkSync setup does not run after connecting a wallet. Need to listen for wallet connection and run it after connecting

**Comment by ceresstation** [comment] 2020-12-02 16:49
A few other minor points:

- [ ] Currently we have a mix of upper and proper case in our CLR Round descriptions, we should standardize to upper case
- [ ] We should reorder grant rounds in ALL lists as follows: INFRA, DAPP, COMMUNITY, REGIONAL (EAST ASIA), APOLLO, LIFTOFF
- [ ] If possible we should consider condensing this down to just one list https://gyazo.com/66349d44947d19af327bc29b1d2b1f7f
- [ ] I have no easy way to show or hide inactive grants or other types of grants I used to be able to toggle

**Comment by jdorfman** [comment] 2020-12-02 17:10
**Issue:** Share Cart URL shows blank page.
**URL:** https://gitcoin.co/grants/cart/bulk-add/40;5;283,366;5;283,567;5;283,886;5;283,:jdorfman
**User Agents:**
macOS 11.0.1 (20B50)
Chrome Version 86.0.4240.198 (Official Build) (x86_64)
Firefox Nightly 85.0a1 (2020-11-22) (64-bit)


![image](https://user-images.githubusercontent.com/398230/100906167-bc525200-347d-11eb-8657-722d2bd7f973.png)
![image](https://user-images.githubusercontent.com/398230/100906240-d2f8a900-347d-11eb-87ea-f4e77d64b829.png)
![image](https://user-images.githubusercontent.com/398230/100906429-076c6500-347e-11eb-9408-757cc227d924.png)

**Comment by jdorfman** [comment] 2020-12-02 17:49
Typo on https://gitcoin.co/grants/cart

> You are additionally contributing 1.25 DAI to the Gitcoin `Mainainter` Grant

Replace with`Maintainer`

![image](https://user-images.githubusercontent.com/398230/100910993-80ba8680-3483-11eb-83b0-ca13dbc64821.png)

**Comment by owocki** [comment] 2020-12-02 17:53
- [ ] looks like theres a bug in which grant edits dont commit https://github.com/gitcoinco/web/issues/7991

**Comment by owocki** [comment] 2020-12-02 17:56
- [ ] twitter cards for each grant show the "what is gitcoin" video when you click them ( video: https://bits.owocki.com/12uKDlbL , tweet example: https://twitter.com/austingriffith/status/1334183770467930112 ).  they should show the grant video, or no video at all.

**Comment by owocki** [comment] 2020-12-02 18:05
- [ ] this grant ( https://gitcoin.co/grants/86/gitcoin-grants-round-8-dev-fund ) has $0 in match despite having $25 contributors https://bits.owocki.com/o0uqQAQ7

**Comment by owocki** [comment] 2020-12-02 18:08
- [ ] nitpicky frontend thing: on the cart, can we pls align the columns so they dont look like crooked teeth? https://bits.owocki.com/rRu0LAGz

**Comment by owocki** [comment] 2020-12-02 18:12
- [ ] shared carts dont work.  here is a test link https://gitcoin.co/grants/cart/bulk-add/40;5;283,1219;5;283,886;5;283,156;5;283,1274;5;283,567;5;283,500;5;283,366;5;283,238;5;283,237;5;283,329;5;283,160;5;283,665;5;283,:owocki - js error https://bits.owocki.com/BluQNPRv

**Comment by ceresstation** [comment] 2020-12-02 18:40
- [ ] Bug with grants created >24h ago not being eligible for CLR? https://gyazo.com/4d07e21a53808316afbe5da8184bc606

Grant in question: https://gitcoin.co/grants/1602/gallerist-by-collectorshub

**Comment by chibie** [comment] 2020-12-02 20:13
> Share Cart URL shows blank page.

- [ ] Share Cart URL shows blank page. pr #8007

cc: @jdorfman

**Comment by vs77bb** [comment] 2020-12-02 20:55
🔵 getting the same request as @ceresstation from rachel, good ghosting.

shows is CLR Eligible in the backend, but when checking out it doesn’t show.

https://gitcoin.co/_administrationgrants/grant/1112/change/ 

![image](https://user-images.githubusercontent.com/23297747/100930226-c47ab380-34b6-11eb-9a22-35c989ed0a54.png)

**Comment by mds1** [comment] 2020-12-02 21:04
@vs77bb @ceresstation If you are a team member of a grant, and add that grant to your cart, it will say "Not eligible for CLR" because you don't get matched for donating to a grant you are part of. Both of those grants seem to be working properly

![image](https://user-images.githubusercontent.com/17163988/100931041-d2bcd580-349e-11eb-8ba7-5241fabd24e4.png)

**Comment by ceresstation** [comment] 2020-12-02 21:08
+1 on making that message more clear for this specific case I'd say something like "Unable to fund a grant you own" or "Unable to fund your own grant"

**Comment by owocki** [comment] 2020-12-02 21:09
```
kevinowocki@local /Users/kevinowocki/Sites/gitcoin/web~ % time curl "https://gitcoin.co/grants/cards_info?page=1&limit=6&sort_option=weighted_shuffle&network=mainnet&keyword=&state=active&collections_page=1&category=&type=all" > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  157k  100  157k    0     0   7127      0  0:00:22  0:00:22 --:--:-- 37765
curl  > /dev/null  0.02s user 0.01s system 0% cpu 22.705 total
```

this API is super slow + causes the grants index page to be slow.

**Comment by ceresstation** [comment] 2020-12-02 21:09
- [ ] the spacing here looks a bit weird I can imagine this becoming spaghetti if someone were part of more that two rounds very quickly: https://gyazo.com/5957dcd54069275e29618658ef7b8cfe?token=6eced74fc4d43b389f77d733f47ec9ea

**Comment by owocki** [comment] 2020-12-03 14:13
- [ ] https://gitcoin.co/_administrationgrants/subscription/51428/change/ this 2 DAI usd contribution seems to be worth $0 according to the amount_per_period_usd - im worried the clr matches will be off if this continues.

**Comment by vs77bb** [comment] 2020-12-03 15:39
collections loading maybe 60% of the time here based on the team call -- https://gitcoin.co/grants/collections?collection_id=13

![image](https://user-images.githubusercontent.com/23297747/101051431-7ebff880-3553-11eb-99ff-0721f7e36dc2.png)

**Comment by vs77bb** [comment] 2020-12-03 16:07
maybe a power-user thing, the 'Sort By' isn't persistent as i scroll down to view grants. makes it hard to sort by matching. 

![image](https://user-images.githubusercontent.com/23297747/101051775-d65e6400-3553-11eb-983f-d96fc6814f15.png)

**Comment by owocki** [comment] 2020-12-03 18:39
https://bits.owocki.com/yAuZvErY

round 7 image still showing u8p

**Comment by owocki** [comment] 2020-12-03 21:02
- [ ] click this link https://gitcoin.co/grants/cart/bulk-add/160;5;283,1561;5;283,1632;5;283,231;5;283,1245;5;283,1147;5;283,202;5;283,1101;5;283,765;5;283,1122;5;283,1211;5;283,143;5;283,275;5;283,490;5;283,1093;5;283,149;5;283,285;5;283,207;5;283,514;5;283,223;5;283,191;5;283,524;5;283,:vpepo and then get taken to the cart page, the grants arent actually in the cart 

video: https://bits.owocki.com/E0u4b5B1

**Comment by teohhanhui** [comment] 2020-12-03 22:19
> TxBatch failed. Reason: zkSync API response error: code 103; message: Tx is incorrect

<details><summary>Screenshot</summary><p>

![Screenshot_2020-12-04 zkSync](https://user-images.githubusercontent.com/548843/101095254-a1f0b380-35f8-11eb-9e6a-e2fa301c7fe9.png)

</p></details>

**Comment by mds1** [comment] 2020-12-03 22:21
Thanks @teohhanhui, I'll relay this to the zkSync team now. What browser and wallet were you using?

**Comment by teohhanhui** [comment] 2020-12-03 23:28
> What browser and wallet were you using?

Firefox 84.0b7 (Manjaro Linux)
WalletConnect (Authereum)

**Comment by developerfred** [comment] 2020-12-04 03:11
@zoek1 #8027

**Comment by vs77bb** [comment] 2020-12-04 17:10
seems like matching in the Matic Round is off -- shows high matching numbers with no donations?

https://gitcoin.co/grants/1530/beyondnft

![image](https://user-images.githubusercontent.com/23297747/101192781-923d9300-3629-11eb-8c78-e50106c0057e.png)

**Comment by vs77bb** [comment] 2020-12-04 22:30
![image](https://user-images.githubusercontent.com/23297747/101221774-6258b480-3656-11eb-8dfc-8b446e0bd3c6.jpeg)

**Closed** 2020-12-18 13:46 UTC
