### ISSUE TITLE
Gas Price Showing as a Funded Issue?

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#1773] opened 2018-07-17 14:17 UTC
**Describe the bug**

Gas price showing in issue explorer as a separate funded issue.

![image 12 12](https://user-images.githubusercontent.com/238235/42823075-a3073ae8-89aa-11e8-9785-5a1bc34a45eb.png)

**Expected behavior**

- [ ] Make it not show

**Comment by owocki** [comment] 2018-07-17 18:01
i think this has to do with the issue with gas prices over the last several weeks and the tx's getting resubmitted

**Comment by owocki** [comment] 2018-07-17 18:01
i can't find these bounties on the explorer? have they been hidden?

**Comment by SaptakS** [comment] 2018-07-18 11:45
I can't reproduce it either.

**Comment by thelostone-mc** [comment] 2018-07-19 06:22
Closing as unable to reproduce ! If it happens again -> we'll reopen it and dig into it

**Closed by thelostone-mc** 2018-07-19 06:22 UTC
Labels: bug
