### ISSUE TITLE
Missing Grants from Profile (Argent / WalletConnect)

### ISSUE THREAD

**Issue by MysticRyuujin** [gitcoinco/web#6874] opened 2020-06-15 19:53 UTC
I used Argent and WalletConnect to fund 6 grants, but they don't show up in my profile.

Originally when I clicked approve on the 2 TX in Argent, Gitcoin website quickly displayed red error messages to me, but then a green success message, I didn't have time to read the errors.

Now, in Argent it looks like the 2 TX failed, but it resubmitted them, and they were successful. I can see the 2 successful TX on Etherscan. But my profile does not show that I donated.

One:
https://etherscan.io/tx/0x249e65515b0e696ede0dc75e7e2781324c6b75e4ac3400edd198d661105b477e

Two:
https://etherscan.io/tx/0xc1bd6155acd06e5a37866dc4787c28045211fb90ac343425593e5860f8625b1a

![SmartSelect_20200615-123810_Argent](https://user-images.githubusercontent.com/8877131/84699911-fe132e80-af17-11ea-8692-409b49d6f115.jpg)

**Comment by owocki** [comment] 2020-06-15 20:12
thanks so much for the report; we did not test in argent/wallet connect.  well get this into the dev queue.

@apbendi @msolomon44 want this? :wink:

**Comment by apbendi** [comment] 2020-06-15 20:13
Thanks @MysticRyuujin can you share the link to the failed transactions?

**Comment by apbendi** [comment] 2020-06-15 20:14
cc @mds1 any thoughts off the top of your head?

**Comment by MysticRyuujin** [comment] 2020-06-15 20:15
One:
0xf184651f527cdf4e0e4424271b4996ef980f4bbbb30c7bb0a9ae4758b0655625

Two:
0x9bd6c2e7d56dcaf66137106c7084592fddbfd907381771616d2066837cd9de62

**Comment by mds1** [comment] 2020-06-15 20:16
No immediate thoughts off the top of my head. I'll try to reproduce this.

@MysticRyuujin Can you provide etherscan links to the failed transactions as well?

**Comment by mds1** [comment] 2020-06-15 20:17
Ah there they are, you beat me 🙂

**Comment by apbendi** [comment] 2020-06-15 20:19
Hey @MysticRyuujin a couple questions:

* When you saw the red error messages, were you still on the cart page?
* When you saw the green success message, were you still on the cart page, or had you been redirected to the grant list page?
* Afterwards, was your cart cleared/emptied, or was it left with items still in it?
* Did you resubmit the txs through Argent or did you do the checkout process again?

Thanks!

**Comment by MysticRyuujin** [comment] 2020-06-15 20:23
So, when the red and green messages appeared it was after the checkout, there's like a little splash screen after you submit?

I don't remember the exact order things happened in but I think it was click checkout, get popup on Argent, click approve twice, see splash screen, red error banners, green success banner, then I was asked to tweet about my fundings.

I did not do anything with Argent, they seemed to have resubmitted all by themselves, like almost immediately too.

And yeah, my cart was empty.

**Comment by apbendi** [comment] 2020-06-15 20:25
Great, thanks for the info @MysticRyuujin, we'll see what we can find.

**Comment by apbendi** [comment] 2020-06-16 13:53
@mds1 was unable to reproduce this with Argent. We have a request out to the Argent team to see if they can tell us why your initial transactions failed, but our current assessment is that the failure was a fluke not necessarily related to the Gitcoin web3 implementaiton.

Regarding your donations, we're working on a script that will slurp up any missed web3 txs and update the database to reflect them, so your contribution will (eventually) be reflected properly.

For now, I think we can close this issue out @owocki, and just keep an eye out for anyone else experiencing similar issues.

**Comment by MysticRyuujin** [comment] 2020-06-16 13:55
Thanks for looking into it ❤️

**Comment by mds1** [comment] 2020-06-17 13:49
Interestingly enough in this case it seems the issue was that the transaction was frontrun. Argent support said the transaction was replayed and replied with these answers to my follow up questions:

> 1. Why was the transaction replayed, i.e. what causes this?
>
> In this particular case the transaction was frontrun. There are no security implications in this case, right now anyone could decide to front run a transaction, and by minting gas tokens they can make a small profit
>
>2. Similarly, how can we prevent this from happening again?
>
> We are working on it on our end, but it might take time, we hope to have a way to prevent it in August.
>
>3. Why are the "From" and "To" addresses different between the two sets of transactions? This seems odd, because I'd expect them to be the same.
>
> The TO is different in that scenario as it was frontrun, and the frontrunner uses a proxy which calls our module.

**Closed** 2020-12-16 15:06 UTC
