### ISSUE TITLE
Donations fail to show up on my gitcoin profile after using zkSync, and also often the regular checkout button is not working.

### ISSUE THREAD

**Issue by Kasimir7** [gitcoinco/web#8558] opened 2021-03-12 05:28 UTC
**Describe the bug**
 My donations dont show up on my gitcoin after using zkSync although everything is appearing to be normal but a bit slow on zk's end ( It took about 8 hours to get the blockconfirmation on zkSync, myetherscan said sucess aafter 30 sec.)

**To Reproduce**
 Sorry I don't have a good Idea for that one.

**Expected behavior**
 Would love the transaction to show up on my gitcoin profile and get the site to work a bit better with my metamask if that is possible. Any help is welcome. Thanks 

**Screenshots**
  Ok, simple discription and links to the transaction. I donated to 4 grants of different categories, community, ntf etc with zkSynk. It seemed that everything went well at first, myetherscan said success and it took about 30 sec for them to confirm my transaction. 

Somehow nothing showed up on my gitcoin profile so I waited a few hours, still noting. 
After a few hours I reached out to the zkSync support on there website and chatted with the support group that gave me following links: https://zkscan.io/explorer/blocks/11980
and https://zkscan.io/explorer/ back at that time the block wasn't processed yet so I waited another 3 or so hours. 

Then success on the block side but still nothing showing up on my gitcoin profile. So I decided to wait another few hours and reach out to a gitcoin team member, and they ask me kindly to describe my issue here and or on discord. 

Somehow I couldn't type in my email and password on discord as it was not showing or typing, so I decided to just post here and hope for some help. Thanks, any help is greatly appreciated. Ah before I forget I also tried this link twice: https://gitcoin.co/grants/add-missing-contributions    with no success ( once just with my wallet address and the other time with the transaction id and my wallet address, and I also waited a few hours still no success.

etherscan : https://etherscan.io/tx/0x1dd6b349770ed2b27a8e07df928ec3c5c5fb536fefa1edeabea955818588522d

Transaction Hash: 0x1dd6b349770ed2b27a8e07df928ec3c5c5fb536fefa1edeabea955818588522d

[Ethereum Transaction Hash (Txhash) Details _ Etherscan.pdf](https://github.com/gitcoinco/web/files/6127738/Ethereum.Transaction.Hash.Txhash.Details._.Etherscan.pdf)

![photo_2021-03-11 19 54 00](https://user-images.githubusercontent.com/34425342/110894406-50fdf480-82a4-11eb-8d74-f6e306d649ad.jpeg)
![photo_2021-03-11 19 53 54](https://user-images.githubusercontent.com/34425342/110894412-52c7b800-82a4-11eb-8f91-01a51374a289.jpeg)

- OS: macOs Big Sur Version 11.2.1
- Browser: Chrome
- Browser Version: Version 89.0.4389.82 (Official Build) (x86_64)
- 
**Smartphone (please complete the following information):** Not using my smartphone for gitcoin much.

- Device: 
- OS: 
- Browser:
- Version:

**Additional context**

**Comment by nopslip** [comment] 2021-03-12 06:57
Thanks for posting up the info. 

> I also tried this link twice: https://gitcoin.co/grants/add-missing-contributions with no success ( once just with my wallet address and the other time with the transaction id and my wallet address, and I also waited a few hours still no success.

This part didn't work for me the first time either. Would you mind trying one more time? With the following process: 

1) make sure you're logged into Metamask and this `0xb09b30f1a4cB051f60Bd6d7Fa61cCbF5334305Ab` account is active and connected in metamask and to gitcoin.co

2) When you click the `add contributions` button is should prompt you to sign a message in Metamask. Once you sign that message it should add missing records to gitcoin.co. 

Can you confirm that you have signed the message successfully?  Please let me know if that works or not. 

Thanks!

**Comment by Kasimir7** [comment] 2021-03-12 07:12
@nopslip Thanks for the answer, yes I tired this many times and it worked for me in the past with the exact same configuration on standart checkout. I tried again as you asked with no success yesterday and today, here are the pictures 

![photo_2021-03-11 22 10 58](https://user-images.githubusercontent.com/34425342/110905280-b529b400-82b6-11eb-82cd-076fcf45767a.jpeg)
![photo_2021-03-11 22 10 52](https://user-images.githubusercontent.com/34425342/110905286-b5c24a80-82b6-11eb-89b6-805e0f7e6605.jpeg)
![photo_2021-03-11 22 10 46](https://user-images.githubusercontent.com/34425342/110905290-b65ae100-82b6-11eb-81e0-6d5e31556a8d.jpeg)
![photo_2021-03-11 22 10 40](https://user-images.githubusercontent.com/34425342/110905292-b6f37780-82b6-11eb-9a7c-90ca5d303f6b.jpeg)

Any idea how to fix this ? Thanks

**Comment by Kasimir7** [comment] 2021-03-12 07:15
Thanks for the reply, I just wrote a comment on GitHub with pictures.
Any idea how to fix it ? Thanks

**Comment by nopslip** [comment] 2021-03-12 15:22
Okay, sounds like you're experiencing two different issues then. Is that correct? 

1) you checked out with zkSync and your grants aren't showing up in gitcoin
2) The standard checkout isn't working for you 

Is that correct? 

If so, can your also provide more info on the standard checkout issue? Is there an error? What exactly happens when you try standard checkout?

**Comment by Kasimir7** [comment] 2021-03-12 20:13
@nopslip Yes, exactly. So for the standard checkout its exactly like in the pictures above... it seems that after clicking the checkout button nothing happens... no meta mask signing etc... since 2 days... as you can see in the pictures above all is connected and I also tried reloading the page... it appears as if the interface is somehow not responding after the first initial click that slightly changes the color of the checkout botton. Any Idea on how to fix that? Also my contributor rank went from 2 to 1 after all these messages with the team... Any idea on how to get points or credit for highlighting  the bugs ? :) Thanks a lot

**Comment by nopslip** [comment] 2021-03-12 20:57
Thanks for the info. I am able to reproduce the issue where the standard checkout button turns light purple and cannot be pressed again but it seems to be related to getting the wallet/browser/site into a bad state. For example, I can reproduce the issue if I use Wallet Connect but I don't open the wallet on my phone.  In short, Gitcoin.co is waiting for the wallet to respond. 

Could you try clearing your browser cache, reloading the site and trying again? I have a feeling this is probably related to your browser, metamask, and/or the site getting into a bad state. 

Also, would you mind opening the dev console to see what happens the first (and second) time you press the standard checkout button? Any errors you can catch there?

**Comment by Kasimir7** [comment] 2021-03-12 21:54
@nopslip Thanks a lot, now the instant checkout works.80$ in gas....  ouch will wait till weekend or so for lower gas fees for some more donations. Any idea on how to fix the rest? Like my previous donations not showing up on gitcoin? The ZkSync admin said they reached out to the gitcoin team and will solve it... that was yesterday. Also now the wallet logo on gitcoin changed from the blue wave to the fox... maybe the issue was due to a new patch that didn't work with old cookies or so?
Thanks a lot, and pls let me know if you have any great ideas for the other issue. 
See old pictures above and new picture below for interface icon change.
![photo_2021-03-12 12 53 02](https://user-images.githubusercontent.com/34425342/111002456-ee533a00-8331-11eb-8b1f-d12745070eee.jpeg)

**Comment by Kasimir7** [comment] 2021-03-12 22:21
@nopslip A little update on the data showing up on my profile now... its still not fully showing but finally this tool:  https://gitcoin.co/grants/add-missing-contributions worked since you helped me fix the gitcoin-metamask interface issue. 
t even shows partially on my spend data on my wall but still not on the total amount spend ... do you thing it will solve itself in a fe min or hours... since it fetched some of the data in other places or could this be another issue? Thanks a lot

![photo_2021-03-12 13 20 59](https://user-images.githubusercontent.com/34425342/111004620-d1b90100-8335-11eb-89dd-b8548002d897.jpeg)
![photo_2021-03-12 13 20 54](https://user-images.githubusercontent.com/34425342/111004623-d382c480-8335-11eb-89e0-f6edcdb2da39.jpeg)

**Comment by Kasimir7** [comment] 2021-03-12 22:29
@nopslip It's solved :) Thanks a lot.

**Comment by Kasimir7** [comment] 2021-03-12 22:31
@nopslip Should I close the issue now? Will it be available for other that have a similar problem ? That would be great. Thanks

**Comment by thelostone-mc** [comment] 2021-03-15 11:40
We close this out @Kasimir7 ! We've got changes coming in to make it more evident that users should head to add-missing-contributions to add their missing txns

**Closed by thelostone-mc** 2021-03-15 11:40 UTC
Labels: gr9-support
