### ISSUE TITLE
One Hacker, One Bounty, Multiple Submissions

### ISSUE THREAD

**Issue by vs77bb** [gitcoinco/web#7180] opened 2020-08-04 17:42 UTC
As a hacker, I want to make multiple submissions to a hackathon / to a specific bounty in certain cases ([like the Sia hackathon](https://gitcoin.co/issue/NebulousLabs/Skynet-Hive/5/100023460)).

**Comment by PixelantDesign** [comment] 2020-10-07 13:06
From Manasi at Sia:

"We don't want to restrict a developer to a single idea - if they have multiple ideas they want to build we want to encourage that - the more the better"

**Comment by thesachinmittal** [comment] 2020-10-15 05:37
This looks perfect. On the same line of thoughts, 

1. That's why we should have an open bounty for every sponsor - every hackathon and brand the prize pot to the developers.
2. Developers need to be informed about the particular sponsor (Through an Overview section) cc: @willsputra 

_If any sponsor make any announcement for developer outreach, 
They will send link to gitcoin tribe page saying, learn more about us + Do this onboarding bounty to learn about us and you would get rewarded. Eventually turning it into a series of milestones. (and gamifying it)_ 
cc: @ceresstation @vs77bb

**Comment by thelostone-mc** [comment] 2020-10-15 08:18
lgtm 👍

**Comment by PixelantDesign** [comment] 2020-10-15 15:07
**Thought from @zoek1 in the figma**

We have two flows, one for normal bounty and the second for hackathon bounty. In hackathon bounties theres an option to select the project that correspond to the submission.

1. I think 'Add Project'  button should pop up the create project modal.
2. Auto select the created project

--------------

Since there are two flows...should we allow this for bounties and hackathons? I think we should, curios if you guys think we should limit it to just hackathons for business reasons? @ceresstation @connoroday

**Comment by octavioamu** [comment] 2020-10-19 15:45
Hey guys I think there are some confusions,
the client ask "we want multiple submissions" and what was designed is multiple links on a submission. That will not solve the request, contributors will need to have all the prs ready when doing the submission, with that the contributions still not able to add new submission another day, or even edit original. 
the design Is missing the relation with projects and how the system work.

**Comment by PixelantDesign** [comment] 2020-10-20 06:05
Hey @octavioamu 

@connoroday /@zoek1  and I debated about this....
one way we discussed was require that the developer create multiple projects.
For example, click start work, fill out the project details. Then allow the person to Add another project in that flow, or display Add another project on issue details.

We thought users might not want to fill out details 3 times, but I could see going this way as well.

**Comment by connoroday** [comment] 2020-10-20 06:27
@octavioamu that was what I was worried about initially - my response to @PixelantDesign's first mockup was: 
"Only question would be, if someone submits one project, then later wants to go and add a second project, can they do it?"

I think the answer is no. We can make it abundantly clear that devs have to submit all their projects at once and to wait until they are all done, but naturally people will mess that up and DM us to get their second project included manually.

Seems like the options here are:
1. Make submission links editable (this would help in other cases too, as you know from the W3F hackathon support @octavioamu)
2. Allow additional submissions after the first, as a whole new piece of data ("Submit work" button turns into "Submit another project" after 1st submission)
3. Make it extremely clear hackers have to have all their submissions ready before clicking the button, but we'll still end up with customer services requests

1 or 2 seems better but I'm not sure which is more complex. I would probably pick # 1 if I could choose

**Comment by PixelantDesign** [comment] 2020-10-23 15:17
**Revised Designs**

**Once hacker has started work, Add Another Project button appears.**
<img width="1248" alt="Screen Shot 2020-10-23 at 11 04 38 AM" src="https://user-images.githubusercontent.com/238235/97021294-a8334080-1520-11eb-8d44-6d21926088a4.png">

**Update Applicants section and call it Projects**
This section will display the work plan and mini project cards with team members
If you have started projects in this case Vporton, you will see set of actions as shown below
<img width="1528" alt="Screen Shot 2020-10-23 at 11 04 17 AM" src="https://user-images.githubusercontent.com/238235/97021367-c13bf180-1520-11eb-8e03-d535b6bcfcda.png">

**The person that submitted work is also able to edit the submission via edit button shown here**
<img width="1255" alt="Screen Shot 2020-10-23 at 11 04 57 AM" src="https://user-images.githubusercontent.com/238235/97021808-4d4e1900-1521-11eb-960b-fa34dcd73646.png">

We could also remove submissions section since sponsors will see submissions in the submission view.
But could be good to have since other community members could see the submissions here. But it's also captured on Github as well.

**Comment by PixelantDesign** [comment] 2020-10-26 18:53
Updated

Show one submit work with tooltip
<img width="1241" alt="Screen Shot 2020-10-26 at 2 51 06 PM" src="https://user-images.githubusercontent.com/238235/97215572-ff444a00-179a-11eb-94ea-827eeba1a958.png">
Show one stop work with tooltip 
<img width="1263" alt="Screen Shot 2020-10-26 at 2 50 55 PM" src="https://user-images.githubusercontent.com/238235/97215510-eb004d00-179a-11eb-9e19-bb33cc40a441.png">


**Show nested projects per start work**
<img width="1481" alt="Screen Shot 2020-10-26 at 2 50 21 PM" src="https://user-images.githubusercontent.com/238235/97215465-da4fd700-179a-11eb-938f-46a1f951b250.png">

**Comment by octavioamu** [comment] 2020-10-26 18:58
Looking good now make more sense @PixelantDesign 
To avoid anyone confusions can you create a build ticket with the definitive design / rules on how it works? 
Once that I can give it a check to see if any technical part is missing and add it if needed.
Sounds good to you?

**Comment by octavioamu** [comment] 2020-10-26 19:03
Also not sure if should be related to this issue or not, do we want to add a new field to prizes need projects or not? 
In that way avoid asking for projects when are prizes with no projects. I don't think any update on design if we want to go that way (just a field on the form or we can even choose that on the admin for the prizes we don't want to generate projects) 
example of what I mean https://gitcoin.co/issue/Polkadot-Network/hello-world-by-polkadot/18/100023944 
Those projects are not actually projects and will end up adding a lot of noice to the projects page you are doing taking place from the important projects we really want to show.

**Comment by frankchen07** [comment] 2020-10-26 22:46
can we review what the data structure will look like for this? I just want to make sure it doesn't break the queries I have currently up that are tracking our metrics.

i think what will happen is it'll just be multiple project IDs associated with one particular bounty, I just need to make sure I don't subsequently rank them out in some deduplication process.

**Comment by PixelantDesign** [comment] 2020-10-27 02:01
>Looking good now make more sense @PixelantDesign
To avoid anyone confusions can you create a build ticket with the definitive design / rules on how it works?
Once that I can give it a check to see if any technical part is missing and add it if needed.
Sounds good to you?

Yes, I will create new ticket @octavioamu

**Comment by PixelantDesign** [comment] 2020-10-27 02:08
>can we review what the data structure will look like for this? I just want to make sure it doesn't break the queries I have currently up that are tracking our metrics.

@frankchen07 multiple project IDs associated **per person** with one particular bounty.

**Comment by PixelantDesign** [comment] 2020-10-27 03:16
Moving this convo to the build ticket https://github.com/gitcoinco/web/issues/7772 cc @zoek1

**Closed** 2020-10-27 03:19 UTC
Labels: Gitcoin Hackathon, discussion
