### ISSUE TITLE
submit work hangs, never opens metamask

### ISSUE THREAD

**Issue by thedavidmeister** [gitcoinco/web#4558] opened 2019-06-01 12:57 UTC
trying to submit work for https://gitcoin.co/issue/NixOS/nixpkgs/59100/2813

using metamask + ledger nano s

have tried on 2 computers, mac and linux

have tried chrome and brave

have tried different GWEI values and other things in the form

have connected metamask to gitcoin through the web popup

have asked for help in slack

submit button always hangs/spins, metamask never opens

**Comment by owocki** [comment] 2019-06-01 14:41
hmmmm.. i cannot reproduce using to just metamask on chrome.  will have to dig up a ledger nano + get it connected.

meantime @thedavidmeister do you see anything in your chrome console (right click anywhere on the page, click 'inspect', then go to 'console + try to submit work).  if there are any javascript errors that will helps us figure this out.

**Comment by thedavidmeister** [comment] 2019-06-03 05:07
ok it worked now? weird...

**Comment by thedavidmeister** [comment] 2019-06-03 05:11
it didn't totally work, the txn for work submitted has confirmations but the gitcoin UI doesn't update to show this:

https://gitcoin.co/issue/NixOS/nixpkgs/59100/2813
https://etherscan.io/tx/0x8cf34cda301a05d13851e5d72ca93ce5ee8afefdd253210e23a4dabbbea21e83

**Comment by owocki** [comment] 2019-06-03 16:00
thanks thats useful to know.  i wonder if theres some callback issue when using a ledger via metamask

looks like the [bounty is now marked as submitted on gitcoin](https://gitcoin.co/issue/NixOS/nixpkgs/59100/2813)

**Comment by thedavidmeister** [comment] 2019-06-04 02:16
ah yes i see, it took almost a whole day to show up >.<

**Closed** 2020-06-02 11:12 UTC
Labels: bug
