### ISSUE TITLE
As a grants user, when I click into a grant, and there are no updates and milestones, the bottom of the page looks cut off

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#3089] opened 2018-12-05 17:39 UTC
### User Story

As a grants user, when I click into a grant, and there are no updates and milestones, the bottom of the page looks cut off

### Why Is this Needed

Looks ugly.

### Current Behavior

<img width="1674" alt="screen shot 2018-12-05 at 12 26 39" src="https://user-images.githubusercontent.com/7516920/49532517-aad41080-f88a-11e8-84b7-2fd454ae505c.png">

### Expected Behavior

Add some whitespace at the bottom so it doesn't look cut off

### Definition of Done
- [x] doesn't look cut off

**Comment by thelostone-mc** [comment] 2018-12-06 16:40
Duplicate of #3095 ?

**Comment by thelostone-mc** [comment] 2018-12-09 12:19
@willsputra / @PixelantDesign  Can we get something going on here ? 
I can throw it in

**Comment by kuhnchris** [comment] 2018-12-09 14:09
Maybe the OSS tree?
![image](https://user-images.githubusercontent.com/761911/49698461-6d41f100-fbc4-11e8-9ebe-ab4daf3720d0.png)
![image](https://user-images.githubusercontent.com/761911/49698462-7a5ee000-fbc4-11e8-92de-73cec18b77fc.png)

**Comment by PixelantDesign** [comment] 2018-12-10 10:20
Frank is referring to the fact that the box is cut off. I don’t recommend throwing in more art to solve the problem.

**Comment by kuhnchris** [comment] 2018-12-10 11:32
The box isn't cut off, it's just directly docked to the blue border... thing with no space (which the above PR fixed).

**Comment by willsputra** [comment] 2018-12-10 13:41
agree with @PixelantDesign. I think the PR works. :)

**Comment by thelostone-mc** [comment] 2018-12-10 17:52
Closing cause @kuhnchris PR took care of this ^_^

**Closed by thelostone-mc** 2018-12-10 17:52 UTC
Labels: Gitcoin Grants, enhancement
