### ISSUE TITLE
Cannot fund an issue in DAI even though DAI has been pre-approved

### ISSUE THREAD

**Issue by b-mueller** [gitcoinco/web#3897] opened 2019-03-06 05:35 UTC
**Describe the bug**
The UI doesn't let me select DAI as form of payment even though I approved it a while ago & have successfully issued DAI bounties before.

I tried logging in and out and clearing the browser cache data which didn't fix the issue.

<img width="1324" alt="screen shot 2019-03-06 at 12 28 20" src="https://user-images.githubusercontent.com/5194767/53858210-e5755280-400b-11e9-99ef-ec9cd74fe113.png">

Also not that DAI is listed twice in the dropdown (but none of the two works for me).

On the token settings page, DAI is shown in the list of approved tokens.

<img width="394" alt="screen shot 2019-03-06 at 12 29 50" src="https://user-images.githubusercontent.com/5194767/53858249-0342b780-400c-11e9-98f6-45cf42e9ab8b.png">

My Ethereum address: 0x0583858adfe7d1d3DC7F8447301cf7B7b056d638

**To Reproduce**

Not sure how to reproduce this.

**Expected behavior**

DAI should be selectable in the dropdown list.

**Desktop (please complete the following information):**

- OS: Mac OS Mojave
- Browse:r Chrome + Metamask
- Browser Version: Laters

**Comment by owocki** [comment] 2019-03-07 00:39
yes looks like you have DAI enabled for this address per

```
// on settings/token page

var from = '0x0583858adfe7d1d3DC7F8447301cf7B7b056d638';
var token_address = '0x89d24a6b4ccb1b6faa2625fe562bdd9a23260359';// DAI
var to = '0x2af47a65da8cd66729b4209c22017d6a5c2d2400'; //stdbounties
var token_contract = web3.eth.contract(token_abi).at(token_address);
var from = web3.eth.coinbase;

token_contract.allowance.call(from, to, function(error, result) {
    console.log(result.toString())
});

```
yet I dont seem to be able to reproeduce this. The UI will only send the orange message if there is an error returning from web3 or if the `result.toNumber() == 0`.  to help me repro, can you confirm that metamask is unlocked, that you're "connected" to Gitcoin, and that you're on the mainnet?  any other repro ideas @b-mueller

**Comment by b-mueller** [comment] 2019-03-08 17:42
Yeah, everything else works including funding with ETH. I can PM you my account credentials if you want to reproduce it?

**Comment by b-mueller** [comment] 2019-03-08 17:42
Oops, I forgot that that would mean giving you my private key 😂

**Comment by b-mueller** [comment] 2019-03-08 17:47
I tried doing it from scratch in a different browser but same result. I don't see any errors in the JavaScript console.

**Comment by owocki** [comment] 2019-03-08 18:48
hmm... so it seems that the consistent repro issue is the account.  let me think on how to repro this and whether any other stuff could help reproduce...

**Comment by b-mueller** [comment] 2019-03-15 07:06
Maybe some mismatch between what's in the DB and on the blockchain? Just guessing...

Anyway, it still doesn't work :(

**Comment by gichiba** [comment] 2019-04-11 10:32
Hey! I am getting the same issue! I've tried emptying my cache and hard re-loading, to no avail. 

If this is a 'manually un-stick' sort of situation I can also provide more details, otherwise will keep watching this space for a fix!

I also am not getting any browser errors, and am able to successfully unlock DAI with the same account on the token page.

**Comment by owocki** [comment] 2019-04-12 05:20
@gichiba ireset your DAI `approve()` on settings/tokens  -- can you try approve()ing again from that page again?

**Comment by gichiba** [comment] 2019-04-12 05:40
Alright! My issue is funded and all is well. Thanks @owocki !

**Comment by thelostone-mc** [comment] 2019-04-12 06:53
Closing this out as this is taken care of ^_^

**Closed by thelostone-mc** 2019-04-12 06:53 UTC
