### ISSUE TITLE
As a bounty funder - web3 not recognized, cannot pay bounties

### ISSUE THREAD

**Issue by rachelhamlin** [gitcoinco/web#5317] opened 2019-10-14 09:24 UTC
As a user, I want Gitcoin to recognize MetaMask so that I can pay out my bounties. 

It appears that Gitcoin is not recognizing web3/MetaMask. I've tried with MetaMask on two desktop browsers and in Status. On all 3 browsers tested, I receive the `Web3 locked. Please unlock Metamask` error. 

**Expected behavior**
Gitcoin recognizes web3 & allows me to fund and pay out bounties.

**Screenshots**

Brave
![image](https://user-images.githubusercontent.com/15470435/66740945-43083200-ee6c-11e9-9caa-ade2367b4b4f.png)

Status
<img src="https://user-images.githubusercontent.com/15470435/66741040-819dec80-ee6c-11e9-9e9d-6a94dfb0478e.PNG" width=250/>

**Desktop (please complete the following information):**

- OS: macOS High Sierra 10.13.6
- Browser: Brave 
- Browser Version: 0.69.135

- Browser: Opera
- Browser Version: 64.0.3417.54

**Smartphone (please complete the following information):**

- Device: iPhone XS Max
- OS: iOS 13.1.2
- Browser: Status
- Version: v1.0 develop build

**Additional context**
I first noticed this last week, 9 or 10/10/19.

**Comment by kuhnchris** [comment] 2019-10-21 07:39
Could you do me a favor and try it in Chrome?
Opera has some own wallet implementation, not sure if that may interfere, same goes for Brave.

**Comment by StatusSceptre** [comment] 2019-10-21 09:06
@kuhnchris I think that's exactly what it is. I'm now on Chrome using our Gitcoin gh account, and it works. I'd just set up a wallet in Brave when this issue first occurred.

**Comment by owocki** [comment] 2019-10-21 16:45
WIP for this : https://github.com/gitcoinco/web/issues/4209

**Comment by StatusSceptre** [comment] 2019-10-30 10:35
Re Status - our desktop browser is only chat right now @owocki. Our mobile betas should allow you to test, so if you want/need to [download](https://status.im/get/) for iOS let me know and I can ensure you're our testflight list.

**Comment by owocki** [comment] 2019-10-30 22:21
this should correct the issue across all non metamask web3 browsers https://github.com/gitcoinco/web/pull/5432

**Comment by owocki** [comment] 2019-11-06 20:16
my PR was merged and deployed today..  You will now no longer see complaints that 'metamask is unlocked' as you use Gitcoin in opera :)

Hat tip to the engineers for helping me get this across the finish line! 

i still need to test across a few other browsers..  that might be somethign that i bounty soon

**Comment by StatusSceptre** [comment] 2019-11-11 09:07
Can confirm our dashboard is now working :) Thanks you guys! This view is helpful.

**Comment by agutsal** [comment] 2019-12-20 17:27
@owocki still getting that:
![image](https://user-images.githubusercontent.com/1643117/71277789-86948600-235e-11ea-9bb7-c37e4e1e919f.png)

Opera `v64.0.3417.92` running on Gentoo Linux.

Metamask connected. Can you confirm it been fixed for you, @rachelhamlin?

**Comment by Sirlupinwatson1** [comment] 2019-12-20 18:13
@owocki  @agutsal @rachelhamlin  I can confirm this. I am getting it to since 2-3 days.

There is an update available only for chrome. I wasn't sure if it was me again the problem, looks like not

**Comment by agutsal** [comment] 2019-12-20 20:01
Seems Opera support should be completely revised.

**Comment by owocki** [comment] 2019-12-20 20:09
guys i appreciate wanting to help but please stop commenting on old tickets looking for new resolutions.

mind adding a new bug at https://github.com/gitcoinco/web/issues/new?assignees=&labels=&template=bug_report.md&title= ? we need to know things like your system specs in order to diagnose the issues

**Comment by Sirlupinwatson1** [comment] 2019-12-21 14:36
> guys i appreciate wanting to help but please stop commenting on old tickets looking for new resolutions.
> 
> mind adding a new bug at https://github.com/gitcoinco/web/issues/new?assignees=&labels=&template=bug_report.md&title= ? we need to know things like your system specs in order to diagnose the issues
> 
> note: i see "Opera v64.0.3417.92 running on Gentoo Linux." from @agutsal but dont know about the others

Hi my friend. How are you doing today ? Sorry to post this here no to confuse anyone. Just passing by and been a while i haven't be in touch wit ya !

**Have a great day** @owocki

**Comment by agutsal** [comment] 2019-12-23 11:03
@owocki  thanks for clarification. You can close that issue, as I have created #5665 
Inviting @rachelhamlin @owocki @Sirlupinwatson1  @kuhnchris and other who might be interested to keep discussing here: #5665

**Closed** 2019-12-23 13:44 UTC
Labels: Web3, bug
