### ISSUE TITLE
Work submitted, but issue is still in "Work started" state

### ISSUE THREAD

**Issue by troggy** [gitcoinco/web#3391] opened 2019-01-03 15:09 UTC
**Describe the bug**
Worker submitted the work, but it's not reflected on Gitcoin page in full (see screenshot). Also "Basic payout" is not available like there is no submission.

https://gitcoin.co/issue/leapdao/solEVM-enforcer/29/1918

![image](https://user-images.githubusercontent.com/163447/50644678-93b83980-0f82-11e9-8492-b8c4b21959f4.png)

**Comment by owocki** [comment] 2019-01-03 18:20
looks to me like your advanced payout of peara didnt go through, thats why the issue is marked as canceled.  ( i dont see it on your ETH address => https://etherscan.io/address/0x6cb117a635dc7633b42089c607fdfc5c60b7d679#tokentxns ) 

this is because advanced payout first cancels the bounty to get the funds back, then sends tips to each recipient you specify.  in this case, since the tip didnt go through, the system assuems it was canceld.

**Comment by owocki** [comment] 2019-01-03 18:20
also the work submitted shows up here => http://bits.owocki.com/cdec34c2093d/Screen%20Shot%202019-01-03%20at%2011.20.26%20AM.png

**Comment by troggy** [comment] 2019-01-04 11:35
> looks to me like your advanced payout of peara didnt go through

what did I make wrong then? After the bounty got cancelled I  received funds back to my address. I used them then to fund the same issue again.

I was surprised that gitcoin allows to cancel the bounty once the work is submitted. What's the point in using the platform to hold the funds, would be much easier to just pay people directly and use the platform only for bounty discovery?

> also the work submitted shows up here 

it started to show up like this only after bounty was cancelled

**Closed** 2020-06-02 11:26 UTC
