### ISSUE TITLE
Personal Email Shows When User Explicitly Uncheck's Display Email

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/web#2152] opened 2018-09-04 03:51 UTC
**Describe the bug**
I just created my first bounty and it shows my personal email in the profile, even though I explicitly said not to show it when I made the bounty post.

**To Reproduce**
Create Bounty - uncheck email

**Expected behavior**
Email should not show

**Screenshots**
![snip20180901_4](https://user-images.githubusercontent.com/238235/45009108-41670c00-afd4-11e8-979a-fb875d2ef4b6.png)

**Additional context**

**Comment by mbeacom** [comment] 2018-09-04 13:43
Possible duplicate of #1387

**Comment by rahulpat** [comment] 2018-09-04 13:58
I have a fix for this, taking the conversation to #1387.

**Comment by PixelantDesign** [comment] 2018-09-04 14:56
Thanks @mbeacom

**Closed** 2018-09-08 07:05 UTC
Labels: bug
