### ISSUE TITLE
A post-hack report which drives a discussion on whether goals were met / likelihood to sponsor again

### ISSUE THREAD

**Issue by frankchen07** [gitcoinco/web#5674] opened 2019-12-23 19:09 UTC
### User Story

A post-hack report which drives a discussion on whether goals were met / likelihood to sponsor again.

### Why Is this Needed

Sponsors want to see their hackathon performance over time so they know how to adjust their spending, marketing, and asks from Gitcoin

### Description

An example chart of a time series metric set:

![Screen Shot 2019-12-23 at 15 39 33](https://user-images.githubusercontent.com/7516920/71385287-5ab21400-259b-11ea-972b-6290aaf3c128.png)

Also useful:

1. new participants vs returning participants (by sponsor?)
2. amount paid historically (most meaningful for the team/project)
3. drive # of entries and # of participants up, and lower cost per entry
4. quality of entries (consensys tracks this based on judges feedback)
5. quality of winners (consensys tracks this based on judges feedback)

### Current Behavior
[comment]: # (Describe what actually happened.)

### Expected Behavior
[comment]: # (Describe what you expected to happen.)

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by alexvotofuture** [comment] 2020-02-19 07:24
Duplicate of #5188 , but some good metrics here to keep in mind for future iterations.

**Closed by alexvotofuture** 2020-02-19 07:24 UTC
Labels: Gitcoin Hackathon, Hackathon Ops
