### ISSUE TITLE
Edited grant description, it didn't change

### ISSUE THREAD

**Issue by DeFiDude** [gitcoinco/web#7991] opened 2020-12-02 05:40 UTC
Wrote up a new description for this round on my grant, saved it, nice. Checked back later (2 mins), its gone and back to the one from last round 3 months ago. :(

Is there anyway to fetch the text from my recent edit? https://gitcoin.co/townsquare?tab=activity:450036 You can see my activity from editing it, but I have no way of viewing the edit and it still says last edited 3 months ago.

Link to my grant: https://gitcoin.co/grants/1101/archivenodeio-the-public-access-ethereum-archive-

Thanks

**Comment by owocki** [comment] 2020-12-02 15:20
@DeFiDude shit. sorry about this man.  

@gitcoinco/engineers i think that theres some backedn task that is causing a race condition here:

1. backend task loads up the grant
2. user edits their grant info/description, click saves
3. backend task saves old version of grant.

is there an easy way to seperate these out so we dont lose the users's updates?

**Comment by octavioamu** [comment] 2020-12-02 18:34
@DeFiDude I just edit the grant to test and worked, Can you try again and let me know? 
What your edit just text? 
Try to hard reload before edit maybe is related to some cached old files on your browser. 
Let me know if you have anything so we can reproduce it.

**Comment by DeFiDude** [comment] 2020-12-02 18:35
Thanks @octavioamu , I just rewrote it this morning and it saved without issue, so all is good now.

**Comment by octavioamu** [comment] 2020-12-02 18:36
ohh thanks @DeFiDude for let me know ping me if you find any other bug or you are able to reproduce this one again.

**Comment by owocki** [comment] 2020-12-02 18:38
@octavioamu this is def still an issue.  its a race condition

1. backend task loads up the grant
2. user edits their grant info/description, click saves
3. backend task saves old version of grant.

this just happeend to me when updating the address of https://gitcoin.co/_administrationgrants/grant/238/change/ 

a mixin that updates only changed fields  would maybe fix this ( https://djangosnippets.org/snippets/2985/ )

**Comment by owocki** [comment] 2020-12-02 18:45
https://gitcoin.co/_administrationgrants/grant/238/change/  

i was just ablke to update this by (1) stopping the celery queuse (2) updating the grant (3) restarting the celery queus - which confirms my theory that this is a race conditoin

**Comment by owocki** [comment] 2020-12-03 14:39
antoher one of these https://github.com/gitcoinco/web/issues/8019

**Comment by owocki** [comment] 2020-12-03 14:48
ok im now 100% certain of the race condition root cause.  i can reproduce by editing prettymuch any grant in the admin + it reverts back pretty  quick

if i `sudo systemctl stop celery.service` on the celery servers first tho, i can edit it.

**Comment by owocki** [comment] 2020-12-04 15:04
ok, the race condition is fixed now.  we fixed it when we fixed the performance issues last night.

@DeFiDude unfortunately we lost your edits though.  im sorry. throwing a few DAI your way to say sorry.

**Comment by thelostone-mc** [comment] 2020-12-07 15:56
Closing this out ! Do reopen if you still face any issues

**Closed by thelostone-mc** 2020-12-07 15:56 UTC
Labels: round-8-support
