### ISSUE TITLE
Missing two grants payments that are shown in the UI for the Rotki grant.

### ISSUE THREAD

**Issue by LefterisJP** [gitcoinco/web#5728] opened 2020-01-08 09:23 UTC
**Describe the bug**

In the [Rotki app grant](https://gitcoin.co/grants/149/rotki?tab=activity) there is as of writing this issue 12 contributions but there are only 10 corresponding transfers on-chain. Around ~30 DAI are missing.

Gitcoin grant page UI:
![2020-01-08-101503_362x89_scrot](https://user-images.githubusercontent.com/1658405/71965421-eebce600-31ff-11ea-8070-5b4d634d5f31.png)

Etherscan UI:
![2020-01-08-101533_363x56_scrot](https://user-images.githubusercontent.com/1658405/71965435-f4b2c700-31ff-11ea-9ba9-db47adcfa0af.png)

https://etherscan.io/address/0x9531c059098e3d194ff87febb587ab07b30b1306

I compared the contributions to etherscsan one by one to see which ones did not make it. And from what I saw these are the culrprits:

The very first contribution:

![2020-01-08-102025_968x94_scrot](https://user-images.githubusercontent.com/1658405/71965727-87536600-3200-11ea-83b6-3515774f60d0.png)

Even in the UI there is no etherscan link so can't even say what is the address we should have received funds from.

The third (and biggest contribution):

https://etherscan.io/tx/0xca29bbe0196f671f564d5bce4dcf4c27eb5fab29ff223ce07ba601c9afbfd44a

![2020-01-08-102132_956x88_scrot](https://user-images.githubusercontent.com/1658405/71965819-b4077d80-3200-11ea-9c59-da00711f965e.png)

It seems that this transfer did not make it into the grant when looking at all the addresses the grant received funds from this (and the 0.8333 DAI one without a link) are the only ones missing.

**To Reproduce**

Not sure. But these 2 transfers did not make it.

**Expected behavior**

Have the same number of transfers as contributions. Also the amount funded should match what the grant creator has received (minus fees ofcourse).

**Comment by markusbkoch** [comment] 2020-01-08 11:59
Not sure about the first one, but the problem with the third one is the same as the one reported in #5723: [approve](https://etherscan.io/tx/0xca29bbe0196f671f564d5bce4dcf4c27eb5fab29ff223ce07ba601c9afbfd44a) transaction went through, but [transfer](https://etherscan.io/tx/0x58b70a143256113beba8f89919dd46ac673c81decd7b4f8b3d4511e80e892811) failed due to insufficient balance.

**Comment by LefterisJP** [comment] 2020-01-08 12:25
It seems you are right @markusbkoch. The problem with the second transaction is indeed due to insufficient balance of the user. So I suppose the second transfer is the same issue as #5723.

I would also like to know what happened in the first transfer though.

**Comment by markusbkoch** [comment] 2020-01-08 14:00
I assume that's a case of ["phantom funding"](https://github.com/gitcoinco/web/issues/5057), with the user having signaled support for 6 projects ($5/6 = 0.8333). I have just signaled support for Ethereum ETL to see what the UI looks like, and it matches what you see in that case.
![image](https://user-images.githubusercontent.com/34865315/71983409-76f1ba00-3205-11ea-8a5b-72b0a9cf1756.png).
So from the description in the link above, I understand Rotki will get the $0.83 at the end of the round.

**Comment by LefterisJP** [comment] 2020-01-08 16:28
Hey @markusbkoch thank you for the insight. That could be it. I guess then that this is something that the Gitcoin website can do better so that we don't end up expecting a transfer and wondering what happened.

I would expect it to be shown as "phantom funding", not be counted to the total, and have an explanation of what it is.

**Comment by owocki** [comment] 2020-01-08 16:34
thanks guys; we are working on a fix for this internally at gitcoin right now

**Comment by LefterisJP** [comment] 2020-01-09 09:13
It seems to have happened again for the Rotki grant @owocki at least 2 times. It would be nice if the solution you guys reach can retroactively fix the interface to display the correct amount funded.

**Comment by owocki** [comment] 2020-01-09 18:39
yes; we are on it!  @danlipert and @thelostone-mc were rolling back some transactions yesterday, planning on getting the rest tomorrow

**Comment by LefterisJP** [comment] 2020-01-10 13:23
Hey @owocki 

This also needs to be disallowed, not just roll back transactions. Someone just did it to poor Antiprosynthesis crediting his grant with 1 million DAI: https://gitcoin.co/grants/160/antiprosynth-twitter-account-activity?tab=activity

Here is the approve: https://etherscan.io/tx/0xe83d42ed1d6305ac099adb61929af921fd8ea3ca61a6585c1c6a840d452bfe02

Needless to say that this should be top priority fix during the round as it's an attack on a grant:

- Malicious user approves a huge amount but spends nothing, credits as many grants as he wants to attack
- The CLR matching system goes completely nuts
- The honest users who would like to contribute to these grants are completely put off as they think that the transactions actually happened and the grant creators are now rich.

**Comment by owocki** [comment] 2020-01-10 14:42
@danlipert said he deleted the tx entries on the grant for the failed txs

here is a ticket to code up a root cause fix for the malicious input to the frontend.  take a look on that ticket and let me know what you think https://github.com/gitcoinco/web/issues/5762

**Comment by danlipert** [comment] 2020-01-10 14:42
@LefterisJP deployed some preventative fixes and some transaction checking code today - we'll stay on the lookout for future fraudulent activity. Thanks for your report

**Comment by poma** [comment] 2020-01-10 14:51
Would be cool to trigger matching rescan as antiprosynth still has $64k in matching

**Comment by owocki** [comment] 2020-01-10 19:11
@poma done!

**Closed** 2020-12-16 14:43 UTC
