### ISSUE TITLE
Facebook trust verification does not work

### ISSUE THREAD

**Issue by BTCAlchemist** [gitcoinco/web#9120] opened 2021-06-16 16:51 UTC
**Describe the bug**

Facebook trust verification does not work

**To Reproduce**

1. On https://gitcoin.co/profile/trust, click Verify under Facebook. This will redirect to a URL like https://www.facebook.com/v9.0/dialog/oauth?response_type=code&client_id=&redirect_uri=https%3A%2F%2Fgitcoin.co%2Fapi%2Fv0.1%2Fprofile%2Fverify_user_facebook&state=HKsocBPy6gvku4BJSNiByx8r3ZYMVP
2. UX flow should show next step for verification but shows, "Invalid App ID
The provided app ID does not look like a valid app ID."

**Expected behavior**

Show next step for Facebook verification

**Screenshots**

![image](https://user-images.githubusercontent.com/56145569/122260487-31203300-ce88-11eb-964f-5a37aed92592.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Brave
- Browser Version: Version 1.25.72 Chromium: 91.0.4472.101 (Official Build) (64-bit)

**Comment by DreadKnight** [comment] 2021-06-16 18:44
Same issues here for months now.
This is duplicate of the recent #9085

**Comment by gdixon** [comment] 2021-06-17 22:29
This is now fixed, please try again @BTCAlchemist 👍

**Closed by gdixon** 2021-06-17 22:29 UTC

**Comment by DreadKnight** [comment] 2021-06-17 22:34
> This is now fixed, please try again @BTCAlchemist

I've just tested and can confirm that it *finally* properly works this time 👍🏻

**Comment by BTCAlchemist** [comment] 2021-06-18 03:58
It works now. Thanks, @gdixon!
