### ISSUE TITLE
DESIGN - as a grants funder, i want to tweet that i just funded a grant, so i can shill how altruistic i am and shill gitcoin grants

### ISSUE THREAD

**Issue by owocki** [gitcoinco/web#4091] opened 2019-04-01 21:46 UTC
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)
as a grants funder, i want to tweet that i just funded a grant, so i can shill how altruistic i am and shill gitcoin grants

### Why Is this Needed
virality, so ppl can show off gitcoin grants contributions

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*:

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*:
feature

### Current Behavior
[comment]: # (Describe what actually happened.)
info dialog pops up after you fund a grant

### Expected Behavior
[comment]: # (Describe what you expected to happen.)
i would like for a modal to pop up when a grant is funded, with a 'tweet about it' button on it so people can show off that they funded a grant.

the modal should have a gitcoin torch bot on it. it should say
H1 - Thanks for contributing!
p - Tell your network about this Gitcoin Grant.  If they fund a grant, the grant owner will get even more Matching Funds! 
Call to Action Button

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)
Design for the above; Pls allow 2-3 iterations

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by owocki** [comment] 2019-04-01 21:46
@pixelantdesign any feedback on this?

@emiwatanabe422 any interest in taking this one on?

**Comment by emiwatanabe422** [comment] 2019-04-02 00:07
@owocki Yes!

**Comment by PixelantDesign** [comment] 2019-04-02 14:20
Great idea! I wonder if we could reuse what we built for inviting Gitcoiners.

cc @SaptakS @octavioamu ?

**Comment by PixelantDesign** [comment] 2019-04-03 14:58
@emiwatanabe422 checkout how we handle social sharing on an issue details page.

**Comment by emiwatanabe422** [comment] 2019-04-03 22:45
@owocki How do we want to store the click count? In the database?  If so, should it be a separate model from `Grants`? Do you use something else for marketing data? Google analytics?

**Comment by owocki** [comment] 2019-04-03 22:53
just a google analytic event should be fine IMHO

**Comment by ceresstation** [comment] 2019-04-08 13:35
Duplicate of https://github.com/gitcoinco/web/issues/3634?

**Closed** 2019-04-08 20:58 UTC
Labels: Gitcoin Grants, marketing
