### ISSUE TITLE
Pin python package versions?

### ISSUE THREAD

**Issue by mbeacom** [gitcoinco/web#145] opened 2017-12-19 01:56 UTC
##### Description
We might want to pin all of our python module versions to avoid explosions in Travis (or live/staging/local for that matter) like #142.

##### Possible Implementation
Pin existing packages in `requirements.txt`, `requirements-dev.txt`, and `requirements-dev.txt`.

**Comment by PixelantDesign** [comment] 2018-07-07 05:10
Need this issue @mbeacom ?

**Comment by danlipert** [comment] 2019-08-07 12:26
dupe of https://github.com/gitcoinco/web/issues/4411

**Closed by danlipert** 2019-08-07 12:26 UTC
Labels: Check: danlipert, Gitcoin.co, To Define
