### ISSUE TITLE
Grant Contribution didn't post on Web

### ISSUE THREAD

**Issue by kevinknielsen** [gitcoinco/web#6328] opened 2020-03-28 15:29 UTC
**Description** 
Contributed a bit to fund the Our Network grant but for some reason, the activity post for the contribution was deleted even though the Ethereum transaction was confirmed.

**Expected behavior**
Was expecting the transaction to post on the grantee's page:
(https://gitcoin.co/grants/565/our-network-community-driven-analytics?tab=transactions)

**Screenshots**
![Screen Shot 2020-03-26 at 14 57 05](https://user-images.githubusercontent.com/35613613/77826650-16c53280-70e7-11ea-9cb5-deb661c490d4.png)

**Desktop (please complete the following information):**

- OS: Mojave
- Browser: Chrome
- Browser Version: 80

**Additional context**
Confirmed Tx id: 0xc7f7e9cab594f9d4bd1c20529a8d641cd3ebbf88c24a43a19ced345aaf799fc8

**Comment by developerfred** [comment] 2020-03-29 22:29
fix the optional view bigFloat  (+1e-18 DAI optional tip to Gitcoin)
<img width="727" alt="Screen Shot 2020-03-29 at 19 25 20" src="https://user-images.githubusercontent.com/57037080/77862617-1b770d00-71f3-11ea-8ca5-23f3cf2de624.png">

**Comment by developerfred** [comment] 2020-03-29 22:30
hey @kevinknielsen, Do you sign other grants? had the same result?

**Comment by owocki** [comment] 2020-03-30 17:42
do you see any errors in console?

i'm also on chrome + i seem to be able to fund this grant ok.. so not sure how to reproduce this

**Comment by thelostone-mc** [comment] 2020-12-22 15:41
Closing this out as we weren't able to reproduce and code has come a long way since then

**Closed by thelostone-mc** 2020-12-22 15:41 UTC
