### ISSUE TITLE
I have contributed and it doesn't show

### ISSUE THREAD

**Issue by Gacisan** [gitcoinco/web#8104] opened 2020-12-13 22:21 UTC
Hey team, 

ive just contributed a small amount of ETH to help with two projects, metamask went thru, etherscan shows success and i havent received any email and it looks like the system didnt note the contribution, even in my cart are still this two project that i backedup. 

What can i do? 

Here is the ID/hash
0x6aeecb71ea43e8fee0e476beba85dd0539db293306c3d586629145bfdc379e08

Please let me know,
Thank you and best regards

**Comment by mds1** [comment] 2020-12-14 20:36
Duplicate of https://github.com/gitcoinco/web/issues/8113

**Closed by mds1** 2020-12-14 20:36 UTC
